// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package quasi_static_padframe_aon_config_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 5;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    struct packed {
      logic [15:0] q;
    } hw_version;
    struct packed {
      logic [15:0] q;
    } padcount;
  } quasi_static_padframe_aon_config_reg2hw_info_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic [1:0]  q;
    } driving_strength;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
  } quasi_static_padframe_aon_config_reg2hw_pad_qs_cfg_reg_t;

  typedef struct packed {
    logic        q;
  } quasi_static_padframe_aon_config_reg2hw_pad_qs_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic [1:0]  q;
    } driving_strength;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
  } quasi_static_padframe_aon_config_reg2hw_pad_io0_cfg_reg_t;

  typedef struct packed {
    logic [1:0]  q;
  } quasi_static_padframe_aon_config_reg2hw_pad_io0_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic [1:0]  q;
    } driving_strength;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
  } quasi_static_padframe_aon_config_reg2hw_pad_io1_cfg_reg_t;

  typedef struct packed {
    logic [1:0]  q;
  } quasi_static_padframe_aon_config_reg2hw_pad_io1_mux_sel_reg_t;

  // Register -> HW type
  typedef struct packed {
    quasi_static_padframe_aon_config_reg2hw_info_reg_t info; // [51:20]
    quasi_static_padframe_aon_config_reg2hw_pad_qs_cfg_reg_t pad_qs_cfg; // [19:15]
    quasi_static_padframe_aon_config_reg2hw_pad_qs_mux_sel_reg_t pad_qs_mux_sel; // [14:14]
    quasi_static_padframe_aon_config_reg2hw_pad_io0_cfg_reg_t pad_io0_cfg; // [13:9]
    quasi_static_padframe_aon_config_reg2hw_pad_io0_mux_sel_reg_t pad_io0_mux_sel; // [8:7]
    quasi_static_padframe_aon_config_reg2hw_pad_io1_cfg_reg_t pad_io1_cfg; // [6:2]
    quasi_static_padframe_aon_config_reg2hw_pad_io1_mux_sel_reg_t pad_io1_mux_sel; // [1:0]
  } quasi_static_padframe_aon_config_reg2hw_t;

  // Register offsets
  parameter logic [BlockAw-1:0] QUASI_STATIC_PADFRAME_AON_CONFIG_INFO_OFFSET = 5'h 0;
  parameter logic [BlockAw-1:0] QUASI_STATIC_PADFRAME_AON_CONFIG_PAD_QS_CFG_OFFSET = 5'h 4;
  parameter logic [BlockAw-1:0] QUASI_STATIC_PADFRAME_AON_CONFIG_PAD_QS_MUX_SEL_OFFSET = 5'h 8;
  parameter logic [BlockAw-1:0] QUASI_STATIC_PADFRAME_AON_CONFIG_PAD_IO0_CFG_OFFSET = 5'h c;
  parameter logic [BlockAw-1:0] QUASI_STATIC_PADFRAME_AON_CONFIG_PAD_IO0_MUX_SEL_OFFSET = 5'h 10;
  parameter logic [BlockAw-1:0] QUASI_STATIC_PADFRAME_AON_CONFIG_PAD_IO1_CFG_OFFSET = 5'h 14;
  parameter logic [BlockAw-1:0] QUASI_STATIC_PADFRAME_AON_CONFIG_PAD_IO1_MUX_SEL_OFFSET = 5'h 18;

  // Register index
  typedef enum int {
    QUASI_STATIC_PADFRAME_AON_CONFIG_INFO,
    QUASI_STATIC_PADFRAME_AON_CONFIG_PAD_QS_CFG,
    QUASI_STATIC_PADFRAME_AON_CONFIG_PAD_QS_MUX_SEL,
    QUASI_STATIC_PADFRAME_AON_CONFIG_PAD_IO0_CFG,
    QUASI_STATIC_PADFRAME_AON_CONFIG_PAD_IO0_MUX_SEL,
    QUASI_STATIC_PADFRAME_AON_CONFIG_PAD_IO1_CFG,
    QUASI_STATIC_PADFRAME_AON_CONFIG_PAD_IO1_MUX_SEL
  } quasi_static_padframe_aon_config_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] QUASI_STATIC_PADFRAME_AON_CONFIG_PERMIT [7] = '{
    4'b 1111, // index[0] QUASI_STATIC_PADFRAME_AON_CONFIG_INFO
    4'b 0001, // index[1] QUASI_STATIC_PADFRAME_AON_CONFIG_PAD_QS_CFG
    4'b 0001, // index[2] QUASI_STATIC_PADFRAME_AON_CONFIG_PAD_QS_MUX_SEL
    4'b 0001, // index[3] QUASI_STATIC_PADFRAME_AON_CONFIG_PAD_IO0_CFG
    4'b 0001, // index[4] QUASI_STATIC_PADFRAME_AON_CONFIG_PAD_IO0_MUX_SEL
    4'b 0001, // index[5] QUASI_STATIC_PADFRAME_AON_CONFIG_PAD_IO1_CFG
    4'b 0001  // index[6] QUASI_STATIC_PADFRAME_AON_CONFIG_PAD_IO1_MUX_SEL
  };

endpackage

