
// File auto-generated by Padrick unknown
package pkg_astral_padframe;

  //Structs for periph

  //Static connections signals
   typedef struct packed {
      logic        fll_alt_clk_o;
      logic        fll_host_clk_o;
      logic        fll_periph_clk_o;
      logic        fll_rt_clk_o;
      logic        hyper_ck_no;
      logic        hyper_ck_o;
      logic        hyper_cs_0_no;
      logic        hyper_cs_1_no;
      logic        hyper_dq_0_o;
      logic        hyper_dq_1_o;
      logic        hyper_dq_2_o;
      logic        hyper_dq_3_o;
      logic        hyper_dq_4_o;
      logic        hyper_dq_5_o;
      logic        hyper_dq_6_o;
      logic        hyper_dq_7_o;
      logic        hyper_dq_oen_i;
      logic        hyper_reset_no;
      logic        hyper_rwds_o;
      logic        hyper_rwds_oen_i;
      logic        jtag_ot_tdo_o;
      logic        jtag_tdo_o;
      logic        uart_tx_o;
     } pad_domain_periph_static_connection_signals_soc2pad_t;

   typedef struct packed {
      logic        boot_mode_0_i;
      logic        boot_mode_1_i;
      logic        fll_bypass_i;
      logic        hyper_dq_0_i;
      logic        hyper_dq_1_i;
      logic        hyper_dq_2_i;
      logic        hyper_dq_3_i;
      logic        hyper_dq_4_i;
      logic        hyper_dq_5_i;
      logic        hyper_dq_6_i;
      logic        hyper_dq_7_i;
      logic        hyper_rwds_i;
      logic        jtag_ot_tclk_i;
      logic        jtag_ot_tdi_i;
      logic        jtag_ot_tms_i;
      logic        jtag_ot_trst_ni;
      logic        jtag_tclk_i;
      logic        jtag_tdi_i;
      logic        jtag_tms_i;
      logic        jtag_trst_ni;
      logic        ot_boot_mode_i;
      logic        pwr_on_rst_ni;
      logic        ref_clk_i;
      logic        secure_boot_i;
      logic        test_mode_i;
      logic        uart_rx_i;
     } pad_domain_periph_static_connection_signals_pad2soc_t;

  // Port Group signals
   typedef struct packed {
      logic        spih_csb_0_o;
      logic        spih_csb_1_o;
      logic        spih_sck_o;
      logic        spih_sd_0_o;
      logic        spih_sd_0_oen_i;
      logic        spih_sd_1_o;
      logic        spih_sd_1_oen_i;
      logic        spih_sd_2_o;
      logic        spih_sd_2_oen_i;
      logic        spih_sd_3_o;
      logic        spih_sd_3_oen_i;
     } pad_domain_periph_port_group_spi_soc2pad_t;

   typedef struct packed {
      logic        spih_sd_0_i;
      logic        spih_sd_1_i;
      logic        spih_sd_2_i;
      logic        spih_sd_3_i;
     } pad_domain_periph_port_group_spi_pad2soc_t;

   typedef struct packed {
      logic        eth_md_o;
      logic        eth_md_oen_i;
      logic        eth_mdc_o;
      logic        eth_rst_no;
      logic        eth_txck_o;
      logic        eth_txctl_o;
      logic        eth_txd_0_o;
      logic        eth_txd_1_o;
      logic        eth_txd_2_o;
      logic        eth_txd_3_o;
     } pad_domain_periph_port_group_ethernet_soc2pad_t;

   typedef struct packed {
      logic        eth_md_i;
      logic        eth_rxck_i;
      logic        eth_rxctl_i;
      logic        eth_rxd_0_i;
      logic        eth_rxd_1_i;
      logic        eth_rxd_2_i;
      logic        eth_rxd_3_i;
     } pad_domain_periph_port_group_ethernet_pad2soc_t;

   typedef struct packed {
      logic        can_tx_o;
     } pad_domain_periph_port_group_can_soc2pad_t;

   typedef struct packed {
      logic        can_rx_i;
     } pad_domain_periph_port_group_can_pad2soc_t;

   typedef struct packed {
      logic        slink_h_0_o;
      logic        slink_h_1_o;
      logic        slink_h_2_o;
      logic        slink_h_3_o;
      logic        slink_rcv_clk_o;
      logic        slink_v_0_o;
      logic        slink_v_1_o;
      logic        slink_v_2_o;
      logic        slink_v_3_o;
     } pad_domain_periph_port_group_serial_link_soc2pad_t;

   typedef struct packed {
      logic        slink_0_i;
      logic        slink_1_i;
      logic        slink_2_i;
      logic        slink_3_i;
      logic        slink_4_i;
      logic        slink_5_i;
      logic        slink_6_i;
      logic        slink_7_i;
      logic        slink_rcv_clk_i;
     } pad_domain_periph_port_group_serial_link_pad2soc_t;

   typedef struct packed {
      logic        i2c_scl_o;
      logic        i2c_scl_oen_i;
      logic        i2c_sda_o;
      logic        i2c_sda_oen_i;
     } pad_domain_periph_port_group_i2c_soc2pad_t;

   typedef struct packed {
      logic        i2c_scl_i;
      logic        i2c_sda_i;
     } pad_domain_periph_port_group_i2c_pad2soc_t;

   typedef struct packed {
      logic        spih_ot_csb_o;
      logic        spih_ot_sck_o;
      logic        spih_ot_sd_0_o;
      logic        spih_ot_sd_0_oen_i;
      logic        spih_ot_sd_1_o;
      logic        spih_ot_sd_1_oen_i;
      logic        spih_ot_sd_2_o;
      logic        spih_ot_sd_2_oen_i;
      logic        spih_ot_sd_3_o;
      logic        spih_ot_sd_3_oen_i;
     } pad_domain_periph_port_group_spi_ot_soc2pad_t;

   typedef struct packed {
      logic        spih_ot_sd_0_i;
      logic        spih_ot_sd_1_i;
      logic        spih_ot_sd_2_i;
      logic        spih_ot_sd_3_i;
     } pad_domain_periph_port_group_spi_ot_pad2soc_t;

   typedef struct packed {
      logic        pll_0_o;
      logic        pll_0_oen_i;
      logic        pll_1_o;
      logic        pll_1_oen_i;
      logic        pll_2_o;
      logic        pll_2_oen_i;
      logic        pll_3_o;
      logic        pll_3_oen_i;
      logic        pll_4_o;
      logic        pll_4_oen_i;
      logic        pll_5_o;
      logic        pll_5_oen_i;
      logic        pll_6_o;
      logic        pll_6_oen_i;
     } pad_domain_periph_port_group_pll_soc2pad_t;

   typedef struct packed {
      logic        pll_0_i;
      logic        pll_1_i;
      logic        pll_2_i;
      logic        pll_3_i;
      logic        pll_4_i;
      logic        pll_5_i;
      logic        pll_6_i;
     } pad_domain_periph_port_group_pll_pad2soc_t;

   typedef struct packed {
      logic        gpio_h_0_o;
      logic        gpio_h_0_oen_i;
      logic        gpio_h_1_o;
      logic        gpio_h_1_oen_i;
      logic        gpio_h_2_o;
      logic        gpio_h_2_oen_i;
      logic        gpio_h_3_o;
      logic        gpio_h_3_oen_i;
      logic        gpio_v_0_o;
      logic        gpio_v_0_oen_i;
      logic        gpio_v_1_o;
      logic        gpio_v_1_oen_i;
      logic        gpio_v_2_o;
      logic        gpio_v_2_oen_i;
      logic        gpio_v_3_o;
      logic        gpio_v_3_oen_i;
      logic        gpio_v_4_o;
      logic        gpio_v_4_oen_i;
      logic        gpio_v_5_o;
      logic        gpio_v_5_oen_i;
      logic        gpio_v_6_o;
      logic        gpio_v_6_oen_i;
      logic        gpio_v_7_o;
      logic        gpio_v_7_oen_i;
      logic        gpio_v_8_o;
      logic        gpio_v_8_oen_i;
      logic        gpio_v_9_o;
      logic        gpio_v_9_oen_i;
      logic        gpio_v_10_o;
      logic        gpio_v_10_oen_i;
      logic        gpio_v_11_o;
      logic        gpio_v_11_oen_i;
      logic        gpio_v_12_o;
      logic        gpio_v_12_oen_i;
      logic        gpio_v_13_o;
      logic        gpio_v_13_oen_i;
      logic        gpio_v_14_o;
      logic        gpio_v_14_oen_i;
      logic        gpio_v_15_o;
      logic        gpio_v_15_oen_i;
      logic        gpio_v_16_o;
      logic        gpio_v_16_oen_i;
      logic        gpio_v_17_o;
      logic        gpio_v_17_oen_i;
     } pad_domain_periph_port_group_gpio_soc2pad_t;

   typedef struct packed {
      logic        gpio_h_0_i;
      logic        gpio_h_1_i;
      logic        gpio_h_2_i;
      logic        gpio_h_3_i;
      logic        gpio_v_0_i;
      logic        gpio_v_1_i;
      logic        gpio_v_2_i;
      logic        gpio_v_3_i;
      logic        gpio_v_4_i;
      logic        gpio_v_5_i;
      logic        gpio_v_6_i;
      logic        gpio_v_7_i;
      logic        gpio_v_8_i;
      logic        gpio_v_9_i;
      logic        gpio_v_10_i;
      logic        gpio_v_11_i;
      logic        gpio_v_12_i;
      logic        gpio_v_13_i;
      logic        gpio_v_14_i;
      logic        gpio_v_15_i;
      logic        gpio_v_16_i;
      logic        gpio_v_17_i;
     } pad_domain_periph_port_group_gpio_pad2soc_t;

   typedef struct packed {
     pad_domain_periph_port_group_spi_soc2pad_t spi;
     pad_domain_periph_port_group_ethernet_soc2pad_t ethernet;
     pad_domain_periph_port_group_can_soc2pad_t can;
     pad_domain_periph_port_group_serial_link_soc2pad_t serial_link;
     pad_domain_periph_port_group_i2c_soc2pad_t i2c;
     pad_domain_periph_port_group_spi_ot_soc2pad_t spi_ot;
     pad_domain_periph_port_group_pll_soc2pad_t pll;
     pad_domain_periph_port_group_gpio_soc2pad_t gpio;
     } pad_domain_periph_ports_soc2pad_t;

   typedef struct packed {
     pad_domain_periph_port_group_spi_pad2soc_t spi;
     pad_domain_periph_port_group_ethernet_pad2soc_t ethernet;
     pad_domain_periph_port_group_can_pad2soc_t can;
     pad_domain_periph_port_group_serial_link_pad2soc_t serial_link;
     pad_domain_periph_port_group_i2c_pad2soc_t i2c;
     pad_domain_periph_port_group_spi_ot_pad2soc_t spi_ot;
     pad_domain_periph_port_group_pll_pad2soc_t pll;
     pad_domain_periph_port_group_gpio_pad2soc_t gpio;
     } pad_domain_periph_ports_pad2soc_t;


  //Toplevel structs

  typedef struct packed {
    pad_domain_periph_static_connection_signals_pad2soc_t periph;
  } static_connection_signals_pad2soc_t;

  typedef struct packed {
    pad_domain_periph_static_connection_signals_soc2pad_t periph;
  } static_connection_signals_soc2pad_t;

  typedef struct packed {
    pad_domain_periph_ports_pad2soc_t periph;
  } port_signals_pad2soc_t;

  typedef struct packed {
    pad_domain_periph_ports_soc2pad_t periph;
  } port_signals_soc2pad_t;


endpackage : pkg_astral_padframe
