// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package modular_padframe_domain_config_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 9;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    struct packed {
      logic [15:0] q;
    } hw_version;
    struct packed {
      logic [15:0] q;
    } padcount;
  } modular_padframe_domain_config_reg2hw_info_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } tx_en;
  } modular_padframe_domain_config_reg2hw_pad_io00_cfg_reg_t;

  typedef struct packed {
    logic [3:0]  q;
  } modular_padframe_domain_config_reg2hw_pad_io00_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } tx_en;
  } modular_padframe_domain_config_reg2hw_pad_io01_cfg_reg_t;

  typedef struct packed {
    logic [3:0]  q;
  } modular_padframe_domain_config_reg2hw_pad_io01_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } tx_en;
  } modular_padframe_domain_config_reg2hw_pad_io02_cfg_reg_t;

  typedef struct packed {
    logic [3:0]  q;
  } modular_padframe_domain_config_reg2hw_pad_io02_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } tx_en;
  } modular_padframe_domain_config_reg2hw_pad_io03_cfg_reg_t;

  typedef struct packed {
    logic [3:0]  q;
  } modular_padframe_domain_config_reg2hw_pad_io03_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } tx_en;
  } modular_padframe_domain_config_reg2hw_pad_io04_cfg_reg_t;

  typedef struct packed {
    logic [3:0]  q;
  } modular_padframe_domain_config_reg2hw_pad_io04_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } tx_en;
  } modular_padframe_domain_config_reg2hw_pad_io05_cfg_reg_t;

  typedef struct packed {
    logic [3:0]  q;
  } modular_padframe_domain_config_reg2hw_pad_io05_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } tx_en;
  } modular_padframe_domain_config_reg2hw_pad_io06_cfg_reg_t;

  typedef struct packed {
    logic [3:0]  q;
  } modular_padframe_domain_config_reg2hw_pad_io06_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } tx_en;
  } modular_padframe_domain_config_reg2hw_pad_io07_cfg_reg_t;

  typedef struct packed {
    logic [3:0]  q;
  } modular_padframe_domain_config_reg2hw_pad_io07_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } tx_en;
  } modular_padframe_domain_config_reg2hw_pad_io08_cfg_reg_t;

  typedef struct packed {
    logic [3:0]  q;
  } modular_padframe_domain_config_reg2hw_pad_io08_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } tx_en;
  } modular_padframe_domain_config_reg2hw_pad_io09_cfg_reg_t;

  typedef struct packed {
    logic [3:0]  q;
  } modular_padframe_domain_config_reg2hw_pad_io09_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } tx_en;
  } modular_padframe_domain_config_reg2hw_pad_io10_cfg_reg_t;

  typedef struct packed {
    logic [3:0]  q;
  } modular_padframe_domain_config_reg2hw_pad_io10_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } tx_en;
  } modular_padframe_domain_config_reg2hw_pad_io11_cfg_reg_t;

  typedef struct packed {
    logic [3:0]  q;
  } modular_padframe_domain_config_reg2hw_pad_io11_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } tx_en;
  } modular_padframe_domain_config_reg2hw_pad_io12_cfg_reg_t;

  typedef struct packed {
    logic [3:0]  q;
  } modular_padframe_domain_config_reg2hw_pad_io12_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } tx_en;
  } modular_padframe_domain_config_reg2hw_pad_io13_cfg_reg_t;

  typedef struct packed {
    logic [3:0]  q;
  } modular_padframe_domain_config_reg2hw_pad_io13_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } tx_en;
  } modular_padframe_domain_config_reg2hw_pad_io14_cfg_reg_t;

  typedef struct packed {
    logic [3:0]  q;
  } modular_padframe_domain_config_reg2hw_pad_io14_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } tx_en;
  } modular_padframe_domain_config_reg2hw_pad_io15_cfg_reg_t;

  typedef struct packed {
    logic [3:0]  q;
  } modular_padframe_domain_config_reg2hw_pad_io15_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } tx_en;
  } modular_padframe_domain_config_reg2hw_pad_io16_cfg_reg_t;

  typedef struct packed {
    logic [3:0]  q;
  } modular_padframe_domain_config_reg2hw_pad_io16_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } tx_en;
  } modular_padframe_domain_config_reg2hw_pad_io17_cfg_reg_t;

  typedef struct packed {
    logic [3:0]  q;
  } modular_padframe_domain_config_reg2hw_pad_io17_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } tx_en;
  } modular_padframe_domain_config_reg2hw_pad_io18_cfg_reg_t;

  typedef struct packed {
    logic [3:0]  q;
  } modular_padframe_domain_config_reg2hw_pad_io18_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } tx_en;
  } modular_padframe_domain_config_reg2hw_pad_io19_cfg_reg_t;

  typedef struct packed {
    logic [3:0]  q;
  } modular_padframe_domain_config_reg2hw_pad_io19_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } tx_en;
  } modular_padframe_domain_config_reg2hw_pad_io20_cfg_reg_t;

  typedef struct packed {
    logic [3:0]  q;
  } modular_padframe_domain_config_reg2hw_pad_io20_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } tx_en;
  } modular_padframe_domain_config_reg2hw_pad_io21_cfg_reg_t;

  typedef struct packed {
    logic [3:0]  q;
  } modular_padframe_domain_config_reg2hw_pad_io21_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } tx_en;
  } modular_padframe_domain_config_reg2hw_pad_io22_cfg_reg_t;

  typedef struct packed {
    logic [3:0]  q;
  } modular_padframe_domain_config_reg2hw_pad_io22_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } tx_en;
  } modular_padframe_domain_config_reg2hw_pad_io23_cfg_reg_t;

  typedef struct packed {
    logic [3:0]  q;
  } modular_padframe_domain_config_reg2hw_pad_io23_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } tx_en;
  } modular_padframe_domain_config_reg2hw_pad_io24_cfg_reg_t;

  typedef struct packed {
    logic [3:0]  q;
  } modular_padframe_domain_config_reg2hw_pad_io24_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } tx_en;
  } modular_padframe_domain_config_reg2hw_pad_io25_cfg_reg_t;

  typedef struct packed {
    logic [3:0]  q;
  } modular_padframe_domain_config_reg2hw_pad_io25_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } tx_en;
  } modular_padframe_domain_config_reg2hw_pad_io26_cfg_reg_t;

  typedef struct packed {
    logic [3:0]  q;
  } modular_padframe_domain_config_reg2hw_pad_io26_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } tx_en;
  } modular_padframe_domain_config_reg2hw_pad_io27_cfg_reg_t;

  typedef struct packed {
    logic [3:0]  q;
  } modular_padframe_domain_config_reg2hw_pad_io27_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } tx_en;
  } modular_padframe_domain_config_reg2hw_pad_io28_cfg_reg_t;

  typedef struct packed {
    logic [3:0]  q;
  } modular_padframe_domain_config_reg2hw_pad_io28_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } tx_en;
  } modular_padframe_domain_config_reg2hw_pad_io29_cfg_reg_t;

  typedef struct packed {
    logic [3:0]  q;
  } modular_padframe_domain_config_reg2hw_pad_io29_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } tx_en;
  } modular_padframe_domain_config_reg2hw_pad_io30_cfg_reg_t;

  typedef struct packed {
    logic [3:0]  q;
  } modular_padframe_domain_config_reg2hw_pad_io30_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } tx_en;
  } modular_padframe_domain_config_reg2hw_pad_io31_cfg_reg_t;

  typedef struct packed {
    logic [3:0]  q;
  } modular_padframe_domain_config_reg2hw_pad_io31_mux_sel_reg_t;

  // Register -> HW type
  typedef struct packed {
    modular_padframe_domain_config_reg2hw_info_reg_t info; // [223:192]
    modular_padframe_domain_config_reg2hw_pad_io00_cfg_reg_t pad_io00_cfg; // [191:190]
    modular_padframe_domain_config_reg2hw_pad_io00_mux_sel_reg_t pad_io00_mux_sel; // [189:186]
    modular_padframe_domain_config_reg2hw_pad_io01_cfg_reg_t pad_io01_cfg; // [185:184]
    modular_padframe_domain_config_reg2hw_pad_io01_mux_sel_reg_t pad_io01_mux_sel; // [183:180]
    modular_padframe_domain_config_reg2hw_pad_io02_cfg_reg_t pad_io02_cfg; // [179:178]
    modular_padframe_domain_config_reg2hw_pad_io02_mux_sel_reg_t pad_io02_mux_sel; // [177:174]
    modular_padframe_domain_config_reg2hw_pad_io03_cfg_reg_t pad_io03_cfg; // [173:172]
    modular_padframe_domain_config_reg2hw_pad_io03_mux_sel_reg_t pad_io03_mux_sel; // [171:168]
    modular_padframe_domain_config_reg2hw_pad_io04_cfg_reg_t pad_io04_cfg; // [167:166]
    modular_padframe_domain_config_reg2hw_pad_io04_mux_sel_reg_t pad_io04_mux_sel; // [165:162]
    modular_padframe_domain_config_reg2hw_pad_io05_cfg_reg_t pad_io05_cfg; // [161:160]
    modular_padframe_domain_config_reg2hw_pad_io05_mux_sel_reg_t pad_io05_mux_sel; // [159:156]
    modular_padframe_domain_config_reg2hw_pad_io06_cfg_reg_t pad_io06_cfg; // [155:154]
    modular_padframe_domain_config_reg2hw_pad_io06_mux_sel_reg_t pad_io06_mux_sel; // [153:150]
    modular_padframe_domain_config_reg2hw_pad_io07_cfg_reg_t pad_io07_cfg; // [149:148]
    modular_padframe_domain_config_reg2hw_pad_io07_mux_sel_reg_t pad_io07_mux_sel; // [147:144]
    modular_padframe_domain_config_reg2hw_pad_io08_cfg_reg_t pad_io08_cfg; // [143:142]
    modular_padframe_domain_config_reg2hw_pad_io08_mux_sel_reg_t pad_io08_mux_sel; // [141:138]
    modular_padframe_domain_config_reg2hw_pad_io09_cfg_reg_t pad_io09_cfg; // [137:136]
    modular_padframe_domain_config_reg2hw_pad_io09_mux_sel_reg_t pad_io09_mux_sel; // [135:132]
    modular_padframe_domain_config_reg2hw_pad_io10_cfg_reg_t pad_io10_cfg; // [131:130]
    modular_padframe_domain_config_reg2hw_pad_io10_mux_sel_reg_t pad_io10_mux_sel; // [129:126]
    modular_padframe_domain_config_reg2hw_pad_io11_cfg_reg_t pad_io11_cfg; // [125:124]
    modular_padframe_domain_config_reg2hw_pad_io11_mux_sel_reg_t pad_io11_mux_sel; // [123:120]
    modular_padframe_domain_config_reg2hw_pad_io12_cfg_reg_t pad_io12_cfg; // [119:118]
    modular_padframe_domain_config_reg2hw_pad_io12_mux_sel_reg_t pad_io12_mux_sel; // [117:114]
    modular_padframe_domain_config_reg2hw_pad_io13_cfg_reg_t pad_io13_cfg; // [113:112]
    modular_padframe_domain_config_reg2hw_pad_io13_mux_sel_reg_t pad_io13_mux_sel; // [111:108]
    modular_padframe_domain_config_reg2hw_pad_io14_cfg_reg_t pad_io14_cfg; // [107:106]
    modular_padframe_domain_config_reg2hw_pad_io14_mux_sel_reg_t pad_io14_mux_sel; // [105:102]
    modular_padframe_domain_config_reg2hw_pad_io15_cfg_reg_t pad_io15_cfg; // [101:100]
    modular_padframe_domain_config_reg2hw_pad_io15_mux_sel_reg_t pad_io15_mux_sel; // [99:96]
    modular_padframe_domain_config_reg2hw_pad_io16_cfg_reg_t pad_io16_cfg; // [95:94]
    modular_padframe_domain_config_reg2hw_pad_io16_mux_sel_reg_t pad_io16_mux_sel; // [93:90]
    modular_padframe_domain_config_reg2hw_pad_io17_cfg_reg_t pad_io17_cfg; // [89:88]
    modular_padframe_domain_config_reg2hw_pad_io17_mux_sel_reg_t pad_io17_mux_sel; // [87:84]
    modular_padframe_domain_config_reg2hw_pad_io18_cfg_reg_t pad_io18_cfg; // [83:82]
    modular_padframe_domain_config_reg2hw_pad_io18_mux_sel_reg_t pad_io18_mux_sel; // [81:78]
    modular_padframe_domain_config_reg2hw_pad_io19_cfg_reg_t pad_io19_cfg; // [77:76]
    modular_padframe_domain_config_reg2hw_pad_io19_mux_sel_reg_t pad_io19_mux_sel; // [75:72]
    modular_padframe_domain_config_reg2hw_pad_io20_cfg_reg_t pad_io20_cfg; // [71:70]
    modular_padframe_domain_config_reg2hw_pad_io20_mux_sel_reg_t pad_io20_mux_sel; // [69:66]
    modular_padframe_domain_config_reg2hw_pad_io21_cfg_reg_t pad_io21_cfg; // [65:64]
    modular_padframe_domain_config_reg2hw_pad_io21_mux_sel_reg_t pad_io21_mux_sel; // [63:60]
    modular_padframe_domain_config_reg2hw_pad_io22_cfg_reg_t pad_io22_cfg; // [59:58]
    modular_padframe_domain_config_reg2hw_pad_io22_mux_sel_reg_t pad_io22_mux_sel; // [57:54]
    modular_padframe_domain_config_reg2hw_pad_io23_cfg_reg_t pad_io23_cfg; // [53:52]
    modular_padframe_domain_config_reg2hw_pad_io23_mux_sel_reg_t pad_io23_mux_sel; // [51:48]
    modular_padframe_domain_config_reg2hw_pad_io24_cfg_reg_t pad_io24_cfg; // [47:46]
    modular_padframe_domain_config_reg2hw_pad_io24_mux_sel_reg_t pad_io24_mux_sel; // [45:42]
    modular_padframe_domain_config_reg2hw_pad_io25_cfg_reg_t pad_io25_cfg; // [41:40]
    modular_padframe_domain_config_reg2hw_pad_io25_mux_sel_reg_t pad_io25_mux_sel; // [39:36]
    modular_padframe_domain_config_reg2hw_pad_io26_cfg_reg_t pad_io26_cfg; // [35:34]
    modular_padframe_domain_config_reg2hw_pad_io26_mux_sel_reg_t pad_io26_mux_sel; // [33:30]
    modular_padframe_domain_config_reg2hw_pad_io27_cfg_reg_t pad_io27_cfg; // [29:28]
    modular_padframe_domain_config_reg2hw_pad_io27_mux_sel_reg_t pad_io27_mux_sel; // [27:24]
    modular_padframe_domain_config_reg2hw_pad_io28_cfg_reg_t pad_io28_cfg; // [23:22]
    modular_padframe_domain_config_reg2hw_pad_io28_mux_sel_reg_t pad_io28_mux_sel; // [21:18]
    modular_padframe_domain_config_reg2hw_pad_io29_cfg_reg_t pad_io29_cfg; // [17:16]
    modular_padframe_domain_config_reg2hw_pad_io29_mux_sel_reg_t pad_io29_mux_sel; // [15:12]
    modular_padframe_domain_config_reg2hw_pad_io30_cfg_reg_t pad_io30_cfg; // [11:10]
    modular_padframe_domain_config_reg2hw_pad_io30_mux_sel_reg_t pad_io30_mux_sel; // [9:6]
    modular_padframe_domain_config_reg2hw_pad_io31_cfg_reg_t pad_io31_cfg; // [5:4]
    modular_padframe_domain_config_reg2hw_pad_io31_mux_sel_reg_t pad_io31_mux_sel; // [3:0]
  } modular_padframe_domain_config_reg2hw_t;

  // Register offsets
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_INFO_OFFSET = 9'h 0;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO00_CFG_OFFSET = 9'h 4;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO00_MUX_SEL_OFFSET = 9'h 8;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO01_CFG_OFFSET = 9'h c;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO01_MUX_SEL_OFFSET = 9'h 10;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO02_CFG_OFFSET = 9'h 14;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO02_MUX_SEL_OFFSET = 9'h 18;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO03_CFG_OFFSET = 9'h 1c;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO03_MUX_SEL_OFFSET = 9'h 20;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO04_CFG_OFFSET = 9'h 24;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO04_MUX_SEL_OFFSET = 9'h 28;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO05_CFG_OFFSET = 9'h 2c;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO05_MUX_SEL_OFFSET = 9'h 30;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO06_CFG_OFFSET = 9'h 34;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO06_MUX_SEL_OFFSET = 9'h 38;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO07_CFG_OFFSET = 9'h 3c;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO07_MUX_SEL_OFFSET = 9'h 40;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO08_CFG_OFFSET = 9'h 44;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO08_MUX_SEL_OFFSET = 9'h 48;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO09_CFG_OFFSET = 9'h 4c;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO09_MUX_SEL_OFFSET = 9'h 50;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO10_CFG_OFFSET = 9'h 54;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO10_MUX_SEL_OFFSET = 9'h 58;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO11_CFG_OFFSET = 9'h 5c;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO11_MUX_SEL_OFFSET = 9'h 60;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO12_CFG_OFFSET = 9'h 64;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO12_MUX_SEL_OFFSET = 9'h 68;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO13_CFG_OFFSET = 9'h 6c;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO13_MUX_SEL_OFFSET = 9'h 70;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO14_CFG_OFFSET = 9'h 74;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO14_MUX_SEL_OFFSET = 9'h 78;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO15_CFG_OFFSET = 9'h 7c;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO15_MUX_SEL_OFFSET = 9'h 80;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO16_CFG_OFFSET = 9'h 84;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO16_MUX_SEL_OFFSET = 9'h 88;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO17_CFG_OFFSET = 9'h 8c;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO17_MUX_SEL_OFFSET = 9'h 90;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO18_CFG_OFFSET = 9'h 94;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO18_MUX_SEL_OFFSET = 9'h 98;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO19_CFG_OFFSET = 9'h 9c;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO19_MUX_SEL_OFFSET = 9'h a0;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO20_CFG_OFFSET = 9'h a4;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO20_MUX_SEL_OFFSET = 9'h a8;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO21_CFG_OFFSET = 9'h ac;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO21_MUX_SEL_OFFSET = 9'h b0;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO22_CFG_OFFSET = 9'h b4;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO22_MUX_SEL_OFFSET = 9'h b8;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO23_CFG_OFFSET = 9'h bc;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO23_MUX_SEL_OFFSET = 9'h c0;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO24_CFG_OFFSET = 9'h c4;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO24_MUX_SEL_OFFSET = 9'h c8;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO25_CFG_OFFSET = 9'h cc;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO25_MUX_SEL_OFFSET = 9'h d0;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO26_CFG_OFFSET = 9'h d4;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO26_MUX_SEL_OFFSET = 9'h d8;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO27_CFG_OFFSET = 9'h dc;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO27_MUX_SEL_OFFSET = 9'h e0;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO28_CFG_OFFSET = 9'h e4;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO28_MUX_SEL_OFFSET = 9'h e8;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO29_CFG_OFFSET = 9'h ec;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO29_MUX_SEL_OFFSET = 9'h f0;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO30_CFG_OFFSET = 9'h f4;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO30_MUX_SEL_OFFSET = 9'h f8;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO31_CFG_OFFSET = 9'h fc;
  parameter logic [BlockAw-1:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO31_MUX_SEL_OFFSET = 9'h 100;

  // Register index
  typedef enum int {
    MODULAR_PADFRAME_DOMAIN_CONFIG_INFO,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO00_CFG,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO00_MUX_SEL,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO01_CFG,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO01_MUX_SEL,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO02_CFG,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO02_MUX_SEL,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO03_CFG,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO03_MUX_SEL,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO04_CFG,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO04_MUX_SEL,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO05_CFG,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO05_MUX_SEL,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO06_CFG,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO06_MUX_SEL,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO07_CFG,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO07_MUX_SEL,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO08_CFG,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO08_MUX_SEL,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO09_CFG,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO09_MUX_SEL,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO10_CFG,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO10_MUX_SEL,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO11_CFG,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO11_MUX_SEL,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO12_CFG,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO12_MUX_SEL,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO13_CFG,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO13_MUX_SEL,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO14_CFG,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO14_MUX_SEL,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO15_CFG,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO15_MUX_SEL,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO16_CFG,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO16_MUX_SEL,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO17_CFG,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO17_MUX_SEL,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO18_CFG,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO18_MUX_SEL,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO19_CFG,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO19_MUX_SEL,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO20_CFG,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO20_MUX_SEL,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO21_CFG,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO21_MUX_SEL,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO22_CFG,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO22_MUX_SEL,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO23_CFG,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO23_MUX_SEL,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO24_CFG,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO24_MUX_SEL,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO25_CFG,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO25_MUX_SEL,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO26_CFG,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO26_MUX_SEL,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO27_CFG,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO27_MUX_SEL,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO28_CFG,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO28_MUX_SEL,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO29_CFG,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO29_MUX_SEL,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO30_CFG,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO30_MUX_SEL,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO31_CFG,
    MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO31_MUX_SEL
  } modular_padframe_domain_config_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] MODULAR_PADFRAME_DOMAIN_CONFIG_PERMIT [65] = '{
    4'b 1111, // index[ 0] MODULAR_PADFRAME_DOMAIN_CONFIG_INFO
    4'b 0001, // index[ 1] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO00_CFG
    4'b 0001, // index[ 2] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO00_MUX_SEL
    4'b 0001, // index[ 3] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO01_CFG
    4'b 0001, // index[ 4] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO01_MUX_SEL
    4'b 0001, // index[ 5] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO02_CFG
    4'b 0001, // index[ 6] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO02_MUX_SEL
    4'b 0001, // index[ 7] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO03_CFG
    4'b 0001, // index[ 8] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO03_MUX_SEL
    4'b 0001, // index[ 9] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO04_CFG
    4'b 0001, // index[10] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO04_MUX_SEL
    4'b 0001, // index[11] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO05_CFG
    4'b 0001, // index[12] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO05_MUX_SEL
    4'b 0001, // index[13] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO06_CFG
    4'b 0001, // index[14] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO06_MUX_SEL
    4'b 0001, // index[15] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO07_CFG
    4'b 0001, // index[16] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO07_MUX_SEL
    4'b 0001, // index[17] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO08_CFG
    4'b 0001, // index[18] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO08_MUX_SEL
    4'b 0001, // index[19] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO09_CFG
    4'b 0001, // index[20] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO09_MUX_SEL
    4'b 0001, // index[21] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO10_CFG
    4'b 0001, // index[22] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO10_MUX_SEL
    4'b 0001, // index[23] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO11_CFG
    4'b 0001, // index[24] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO11_MUX_SEL
    4'b 0001, // index[25] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO12_CFG
    4'b 0001, // index[26] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO12_MUX_SEL
    4'b 0001, // index[27] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO13_CFG
    4'b 0001, // index[28] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO13_MUX_SEL
    4'b 0001, // index[29] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO14_CFG
    4'b 0001, // index[30] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO14_MUX_SEL
    4'b 0001, // index[31] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO15_CFG
    4'b 0001, // index[32] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO15_MUX_SEL
    4'b 0001, // index[33] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO16_CFG
    4'b 0001, // index[34] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO16_MUX_SEL
    4'b 0001, // index[35] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO17_CFG
    4'b 0001, // index[36] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO17_MUX_SEL
    4'b 0001, // index[37] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO18_CFG
    4'b 0001, // index[38] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO18_MUX_SEL
    4'b 0001, // index[39] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO19_CFG
    4'b 0001, // index[40] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO19_MUX_SEL
    4'b 0001, // index[41] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO20_CFG
    4'b 0001, // index[42] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO20_MUX_SEL
    4'b 0001, // index[43] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO21_CFG
    4'b 0001, // index[44] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO21_MUX_SEL
    4'b 0001, // index[45] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO22_CFG
    4'b 0001, // index[46] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO22_MUX_SEL
    4'b 0001, // index[47] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO23_CFG
    4'b 0001, // index[48] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO23_MUX_SEL
    4'b 0001, // index[49] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO24_CFG
    4'b 0001, // index[50] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO24_MUX_SEL
    4'b 0001, // index[51] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO25_CFG
    4'b 0001, // index[52] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO25_MUX_SEL
    4'b 0001, // index[53] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO26_CFG
    4'b 0001, // index[54] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO26_MUX_SEL
    4'b 0001, // index[55] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO27_CFG
    4'b 0001, // index[56] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO27_MUX_SEL
    4'b 0001, // index[57] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO28_CFG
    4'b 0001, // index[58] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO28_MUX_SEL
    4'b 0001, // index[59] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO29_CFG
    4'b 0001, // index[60] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO29_MUX_SEL
    4'b 0001, // index[61] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO30_CFG
    4'b 0001, // index[62] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO30_MUX_SEL
    4'b 0001, // index[63] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO31_CFG
    4'b 0001  // index[64] MODULAR_PADFRAME_DOMAIN_CONFIG_PAD_IO31_MUX_SEL
  };

endpackage

