
module kraken_padframe_aon
  import pkg_kraken_padframe::*;
  import pkg_internal_kraken_padframe_aon::*;
#(
  parameter type              req_t  = logic, // reg_interface request type
  parameter type             resp_t  = logic // reg_interface response type
) (
  input logic clk_i,
  input logic rst_ni,
  output pad_domain_aon_static_connection_signals_pad2soc_t static_connection_signals_pad2soc,
  input pad_domain_aon_static_connection_signals_soc2pad_t static_connection_signals_soc2pad,
  output pad_domain_aon_ports_pad2soc_t port_signals_pad2soc_o,
  input pad_domain_aon_ports_soc2pad_t port_signals_soc2pad_i,
  inout wire logic pad_pad_bypass_fll_pad,
  inout wire logic pad_pad_ext_clk_pad,
  inout wire logic pad_pad_ref_clk_pad,
  inout wire logic pad_pad_bootsel0_pad,
  inout wire logic pad_pad_bootsel1_pad,
  inout wire logic pad_pad_bypass_pad,
  inout wire logic pad_pad_reset_pad,
  inout wire logic pad_pad_jtag_tck_pad,
  inout wire logic pad_pad_jtag_tms_pad,
  inout wire logic pad_pad_jtag_tdi_pad,
  inout wire logic pad_pad_jtag_trstn_pad,
  inout wire logic pad_pad_jtag_tdo_pad,
  inout wire logic pad_pad_hyp_cs0_pad,
  inout wire logic pad_pad_hyp_cs1_pad,
  inout wire logic pad_pad_hyp_ck_pad,
  inout wire logic pad_pad_hyp_ckn_pad,
  inout wire logic pad_pad_hyp_rwds_pad,
  inout wire logic pad_pad_hyp_reset_pad,
  inout wire logic pad_pad_hyp_dq0_pad,
  inout wire logic pad_pad_hyp_dq1_pad,
  inout wire logic pad_pad_hyp_dq2_pad,
  inout wire logic pad_pad_hyp_dq3_pad,
  inout wire logic pad_pad_hyp_dq4_pad,
  inout wire logic pad_pad_hyp_dq5_pad,
  inout wire logic pad_pad_hyp_dq6_pad,
  inout wire logic pad_pad_hyp_dq7_pad,
  inout wire logic pad_pad_gpioa0_pad,
  inout wire logic pad_pad_gpioa1_pad,
  inout wire logic pad_pad_gpioa2_pad,
  inout wire logic pad_pad_gpioa3_pad,
  inout wire logic pad_pad_gpioa4_pad,
  inout wire logic pad_pad_gpioa5_pad,
  inout wire logic pad_pad_gpioa6_pad,
  inout wire logic pad_pad_gpioa7_pad,
  inout wire logic pad_pad_gpioa8_pad,
  inout wire logic pad_pad_gpioa9_pad,
  inout wire logic pad_pad_gpioa10_pad,
  inout wire logic pad_pad_gpioa11_pad,
  inout wire logic pad_pad_gpioa12_pad,
  inout wire logic pad_pad_gpioa13_pad,
  inout wire logic pad_pad_gpioa14_pad,
  inout wire logic pad_pad_gpioa15_pad,
  inout wire logic pad_pad_gpioa16_pad,
  inout wire logic pad_pad_gpioa17_pad,
  inout wire logic pad_pad_gpioa18_pad,
  inout wire logic pad_pad_gpioa19_pad,
  inout wire logic pad_pad_gpioa20_pad,
  inout wire logic pad_pad_gpioa21_pad,
  inout wire logic pad_pad_gpioa22_pad,
  inout wire logic pad_pad_gpioa23_pad,
  inout wire logic pad_pad_gpioa24_pad,
  inout wire logic pad_pad_gpioa25_pad,
  inout wire logic pad_pad_gpiob0_pad,
  inout wire logic pad_pad_gpiob1_pad,
  inout wire logic pad_pad_gpiob2_pad,
  inout wire logic pad_pad_gpiob3_pad,
  inout wire logic pad_pad_gpiob4_pad,
  inout wire logic pad_pad_gpiob5_pad,
  inout wire logic pad_pad_gpiob6_pad,
  inout wire logic pad_pad_gpiob7_pad,
  inout wire logic pad_pad_gpiob8_pad,
  inout wire logic pad_pad_gpiob9_pad,
  inout wire logic pad_pad_gpiob10_pad,
  inout wire logic pad_pad_gpiob11_pad,
  inout wire logic pad_pad_gpiob12_pad,
  inout wire logic pad_pad_gpiob13_pad,
  inout wire logic pad_pad_gpiob14_pad,
  inout wire logic pad_pad_gpiob15_pad,
  input req_t config_req_i,
  output resp_t config_rsp_o
);

   mux_to_pads_t s_mux_to_pads;
   pads_to_mux_t s_pads_to_mux;

   kraken_padframe_aon_pads i_aon_pads (
     .static_connection_signals_pad2soc,
     .static_connection_signals_soc2pad,
     .mux_to_pads_i(s_mux_to_pads),
     .pads_to_mux_o(s_pads_to_mux),
     .pad_pad_bypass_fll_pad,
     .pad_pad_ext_clk_pad,
     .pad_pad_ref_clk_pad,
     .pad_pad_bootsel0_pad,
     .pad_pad_bootsel1_pad,
     .pad_pad_bypass_pad,
     .pad_pad_reset_pad,
     .pad_pad_jtag_tck_pad,
     .pad_pad_jtag_tms_pad,
     .pad_pad_jtag_tdi_pad,
     .pad_pad_jtag_trstn_pad,
     .pad_pad_jtag_tdo_pad,
     .pad_pad_hyp_cs0_pad,
     .pad_pad_hyp_cs1_pad,
     .pad_pad_hyp_ck_pad,
     .pad_pad_hyp_ckn_pad,
     .pad_pad_hyp_rwds_pad,
     .pad_pad_hyp_reset_pad,
     .pad_pad_hyp_dq0_pad,
     .pad_pad_hyp_dq1_pad,
     .pad_pad_hyp_dq2_pad,
     .pad_pad_hyp_dq3_pad,
     .pad_pad_hyp_dq4_pad,
     .pad_pad_hyp_dq5_pad,
     .pad_pad_hyp_dq6_pad,
     .pad_pad_hyp_dq7_pad,
     .pad_pad_gpioa0_pad,
     .pad_pad_gpioa1_pad,
     .pad_pad_gpioa2_pad,
     .pad_pad_gpioa3_pad,
     .pad_pad_gpioa4_pad,
     .pad_pad_gpioa5_pad,
     .pad_pad_gpioa6_pad,
     .pad_pad_gpioa7_pad,
     .pad_pad_gpioa8_pad,
     .pad_pad_gpioa9_pad,
     .pad_pad_gpioa10_pad,
     .pad_pad_gpioa11_pad,
     .pad_pad_gpioa12_pad,
     .pad_pad_gpioa13_pad,
     .pad_pad_gpioa14_pad,
     .pad_pad_gpioa15_pad,
     .pad_pad_gpioa16_pad,
     .pad_pad_gpioa17_pad,
     .pad_pad_gpioa18_pad,
     .pad_pad_gpioa19_pad,
     .pad_pad_gpioa20_pad,
     .pad_pad_gpioa21_pad,
     .pad_pad_gpioa22_pad,
     .pad_pad_gpioa23_pad,
     .pad_pad_gpioa24_pad,
     .pad_pad_gpioa25_pad,
     .pad_pad_gpiob0_pad,
     .pad_pad_gpiob1_pad,
     .pad_pad_gpiob2_pad,
     .pad_pad_gpiob3_pad,
     .pad_pad_gpiob4_pad,
     .pad_pad_gpiob5_pad,
     .pad_pad_gpiob6_pad,
     .pad_pad_gpiob7_pad,
     .pad_pad_gpiob8_pad,
     .pad_pad_gpiob9_pad,
     .pad_pad_gpiob10_pad,
     .pad_pad_gpiob11_pad,
     .pad_pad_gpiob12_pad,
     .pad_pad_gpiob13_pad,
     .pad_pad_gpiob14_pad,
     .pad_pad_gpiob15_pad

  );

   kraken_padframe_aon_muxer #(
     .req_t(req_t),
     .resp_t(resp_t)
   )i_aon_muxer (
     .clk_i,
     .rst_ni,
     .port_signals_soc2pad_i,
     .port_signals_pad2soc_o,
     .mux_to_pads_o(s_mux_to_pads),
     .pads_to_mux_i(s_pads_to_mux),
     // Configuration interface using register_interface protocol
     .config_req_i,
     .config_rsp_o
   );

endmodule : kraken_padframe_aon
