// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package kraken_padframe_aon_config_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 9;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    struct packed {
      logic [15:0] q;
    } hw_version;
    struct packed {
      logic [15:0] q;
    } padcount;
  } kraken_padframe_aon_config_reg2hw_info_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic [1:0]  q;
    } drv;
    struct packed {
      logic        q;
    } pde;
    struct packed {
      logic        q;
    } pue;
    struct packed {
      logic        q;
    } rxe;
    struct packed {
      logic        q;
    } slw;
    struct packed {
      logic        q;
    } smt;
    struct packed {
      logic        q;
    } trie;
  } kraken_padframe_aon_config_reg2hw_pad_gpioa0_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } kraken_padframe_aon_config_reg2hw_pad_gpioa0_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic [1:0]  q;
    } drv;
    struct packed {
      logic        q;
    } pde;
    struct packed {
      logic        q;
    } pue;
    struct packed {
      logic        q;
    } rxe;
    struct packed {
      logic        q;
    } slw;
    struct packed {
      logic        q;
    } smt;
    struct packed {
      logic        q;
    } trie;
  } kraken_padframe_aon_config_reg2hw_pad_gpioa1_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } kraken_padframe_aon_config_reg2hw_pad_gpioa1_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic [1:0]  q;
    } drv;
    struct packed {
      logic        q;
    } pde;
    struct packed {
      logic        q;
    } pue;
    struct packed {
      logic        q;
    } rxe;
    struct packed {
      logic        q;
    } slw;
    struct packed {
      logic        q;
    } smt;
    struct packed {
      logic        q;
    } trie;
  } kraken_padframe_aon_config_reg2hw_pad_gpioa2_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } kraken_padframe_aon_config_reg2hw_pad_gpioa2_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic [1:0]  q;
    } drv;
    struct packed {
      logic        q;
    } pde;
    struct packed {
      logic        q;
    } pue;
    struct packed {
      logic        q;
    } rxe;
    struct packed {
      logic        q;
    } slw;
    struct packed {
      logic        q;
    } smt;
    struct packed {
      logic        q;
    } trie;
  } kraken_padframe_aon_config_reg2hw_pad_gpioa3_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } kraken_padframe_aon_config_reg2hw_pad_gpioa3_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic [1:0]  q;
    } drv;
    struct packed {
      logic        q;
    } pde;
    struct packed {
      logic        q;
    } pue;
    struct packed {
      logic        q;
    } rxe;
    struct packed {
      logic        q;
    } slw;
    struct packed {
      logic        q;
    } smt;
    struct packed {
      logic        q;
    } trie;
  } kraken_padframe_aon_config_reg2hw_pad_gpioa4_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } kraken_padframe_aon_config_reg2hw_pad_gpioa4_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic [1:0]  q;
    } drv;
    struct packed {
      logic        q;
    } pde;
    struct packed {
      logic        q;
    } pue;
    struct packed {
      logic        q;
    } rxe;
    struct packed {
      logic        q;
    } slw;
    struct packed {
      logic        q;
    } smt;
    struct packed {
      logic        q;
    } trie;
  } kraken_padframe_aon_config_reg2hw_pad_gpioa5_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } kraken_padframe_aon_config_reg2hw_pad_gpioa5_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic [1:0]  q;
    } drv;
    struct packed {
      logic        q;
    } pde;
    struct packed {
      logic        q;
    } pue;
    struct packed {
      logic        q;
    } rxe;
    struct packed {
      logic        q;
    } slw;
    struct packed {
      logic        q;
    } smt;
    struct packed {
      logic        q;
    } trie;
  } kraken_padframe_aon_config_reg2hw_pad_gpioa6_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } kraken_padframe_aon_config_reg2hw_pad_gpioa6_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic [1:0]  q;
    } drv;
    struct packed {
      logic        q;
    } pde;
    struct packed {
      logic        q;
    } pue;
    struct packed {
      logic        q;
    } rxe;
    struct packed {
      logic        q;
    } slw;
    struct packed {
      logic        q;
    } smt;
    struct packed {
      logic        q;
    } trie;
  } kraken_padframe_aon_config_reg2hw_pad_gpioa7_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } kraken_padframe_aon_config_reg2hw_pad_gpioa7_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic [1:0]  q;
    } drv;
    struct packed {
      logic        q;
    } pde;
    struct packed {
      logic        q;
    } pue;
    struct packed {
      logic        q;
    } rxe;
    struct packed {
      logic        q;
    } slw;
    struct packed {
      logic        q;
    } smt;
    struct packed {
      logic        q;
    } trie;
  } kraken_padframe_aon_config_reg2hw_pad_gpioa8_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } kraken_padframe_aon_config_reg2hw_pad_gpioa8_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic [1:0]  q;
    } drv;
    struct packed {
      logic        q;
    } pde;
    struct packed {
      logic        q;
    } pue;
    struct packed {
      logic        q;
    } rxe;
    struct packed {
      logic        q;
    } slw;
    struct packed {
      logic        q;
    } smt;
    struct packed {
      logic        q;
    } trie;
  } kraken_padframe_aon_config_reg2hw_pad_gpioa9_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } kraken_padframe_aon_config_reg2hw_pad_gpioa9_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic [1:0]  q;
    } drv;
    struct packed {
      logic        q;
    } pde;
    struct packed {
      logic        q;
    } pue;
    struct packed {
      logic        q;
    } rxe;
    struct packed {
      logic        q;
    } slw;
    struct packed {
      logic        q;
    } smt;
    struct packed {
      logic        q;
    } trie;
  } kraken_padframe_aon_config_reg2hw_pad_gpioa10_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } kraken_padframe_aon_config_reg2hw_pad_gpioa10_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic [1:0]  q;
    } drv;
    struct packed {
      logic        q;
    } pde;
    struct packed {
      logic        q;
    } pue;
    struct packed {
      logic        q;
    } rxe;
    struct packed {
      logic        q;
    } slw;
    struct packed {
      logic        q;
    } smt;
    struct packed {
      logic        q;
    } trie;
  } kraken_padframe_aon_config_reg2hw_pad_gpioa11_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } kraken_padframe_aon_config_reg2hw_pad_gpioa11_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic [1:0]  q;
    } drv;
    struct packed {
      logic        q;
    } pde;
    struct packed {
      logic        q;
    } pue;
    struct packed {
      logic        q;
    } rxe;
    struct packed {
      logic        q;
    } slw;
    struct packed {
      logic        q;
    } smt;
    struct packed {
      logic        q;
    } trie;
  } kraken_padframe_aon_config_reg2hw_pad_gpioa12_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } kraken_padframe_aon_config_reg2hw_pad_gpioa12_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic [1:0]  q;
    } drv;
    struct packed {
      logic        q;
    } pde;
    struct packed {
      logic        q;
    } pue;
    struct packed {
      logic        q;
    } rxe;
    struct packed {
      logic        q;
    } slw;
    struct packed {
      logic        q;
    } smt;
    struct packed {
      logic        q;
    } trie;
  } kraken_padframe_aon_config_reg2hw_pad_gpioa13_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } kraken_padframe_aon_config_reg2hw_pad_gpioa13_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic [1:0]  q;
    } drv;
    struct packed {
      logic        q;
    } pde;
    struct packed {
      logic        q;
    } pue;
    struct packed {
      logic        q;
    } rxe;
    struct packed {
      logic        q;
    } slw;
    struct packed {
      logic        q;
    } smt;
    struct packed {
      logic        q;
    } trie;
  } kraken_padframe_aon_config_reg2hw_pad_gpioa14_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } kraken_padframe_aon_config_reg2hw_pad_gpioa14_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic [1:0]  q;
    } drv;
    struct packed {
      logic        q;
    } pde;
    struct packed {
      logic        q;
    } pue;
    struct packed {
      logic        q;
    } rxe;
    struct packed {
      logic        q;
    } slw;
    struct packed {
      logic        q;
    } smt;
    struct packed {
      logic        q;
    } trie;
  } kraken_padframe_aon_config_reg2hw_pad_gpioa15_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } kraken_padframe_aon_config_reg2hw_pad_gpioa15_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic [1:0]  q;
    } drv;
    struct packed {
      logic        q;
    } pde;
    struct packed {
      logic        q;
    } pue;
    struct packed {
      logic        q;
    } rxe;
    struct packed {
      logic        q;
    } slw;
    struct packed {
      logic        q;
    } smt;
    struct packed {
      logic        q;
    } trie;
  } kraken_padframe_aon_config_reg2hw_pad_gpioa16_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } kraken_padframe_aon_config_reg2hw_pad_gpioa16_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic [1:0]  q;
    } drv;
    struct packed {
      logic        q;
    } pde;
    struct packed {
      logic        q;
    } pue;
    struct packed {
      logic        q;
    } rxe;
    struct packed {
      logic        q;
    } slw;
    struct packed {
      logic        q;
    } smt;
    struct packed {
      logic        q;
    } trie;
  } kraken_padframe_aon_config_reg2hw_pad_gpioa17_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } kraken_padframe_aon_config_reg2hw_pad_gpioa17_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic [1:0]  q;
    } drv;
    struct packed {
      logic        q;
    } pde;
    struct packed {
      logic        q;
    } pue;
    struct packed {
      logic        q;
    } rxe;
    struct packed {
      logic        q;
    } slw;
    struct packed {
      logic        q;
    } smt;
    struct packed {
      logic        q;
    } trie;
  } kraken_padframe_aon_config_reg2hw_pad_gpioa18_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } kraken_padframe_aon_config_reg2hw_pad_gpioa18_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic [1:0]  q;
    } drv;
    struct packed {
      logic        q;
    } pde;
    struct packed {
      logic        q;
    } pue;
    struct packed {
      logic        q;
    } rxe;
    struct packed {
      logic        q;
    } slw;
    struct packed {
      logic        q;
    } smt;
    struct packed {
      logic        q;
    } trie;
  } kraken_padframe_aon_config_reg2hw_pad_gpioa19_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } kraken_padframe_aon_config_reg2hw_pad_gpioa19_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic [1:0]  q;
    } drv;
    struct packed {
      logic        q;
    } pde;
    struct packed {
      logic        q;
    } pue;
    struct packed {
      logic        q;
    } rxe;
    struct packed {
      logic        q;
    } slw;
    struct packed {
      logic        q;
    } smt;
    struct packed {
      logic        q;
    } trie;
  } kraken_padframe_aon_config_reg2hw_pad_gpioa20_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } kraken_padframe_aon_config_reg2hw_pad_gpioa20_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic [1:0]  q;
    } drv;
    struct packed {
      logic        q;
    } pde;
    struct packed {
      logic        q;
    } pue;
    struct packed {
      logic        q;
    } rxe;
    struct packed {
      logic        q;
    } slw;
    struct packed {
      logic        q;
    } smt;
    struct packed {
      logic        q;
    } trie;
  } kraken_padframe_aon_config_reg2hw_pad_gpioa21_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } kraken_padframe_aon_config_reg2hw_pad_gpioa21_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic [1:0]  q;
    } drv;
    struct packed {
      logic        q;
    } pde;
    struct packed {
      logic        q;
    } pue;
    struct packed {
      logic        q;
    } rxe;
    struct packed {
      logic        q;
    } slw;
    struct packed {
      logic        q;
    } smt;
    struct packed {
      logic        q;
    } trie;
  } kraken_padframe_aon_config_reg2hw_pad_gpioa22_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } kraken_padframe_aon_config_reg2hw_pad_gpioa22_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic [1:0]  q;
    } drv;
    struct packed {
      logic        q;
    } pde;
    struct packed {
      logic        q;
    } pue;
    struct packed {
      logic        q;
    } rxe;
    struct packed {
      logic        q;
    } slw;
    struct packed {
      logic        q;
    } smt;
    struct packed {
      logic        q;
    } trie;
  } kraken_padframe_aon_config_reg2hw_pad_gpioa23_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } kraken_padframe_aon_config_reg2hw_pad_gpioa23_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic [1:0]  q;
    } drv;
    struct packed {
      logic        q;
    } pde;
    struct packed {
      logic        q;
    } pue;
    struct packed {
      logic        q;
    } rxe;
    struct packed {
      logic        q;
    } slw;
    struct packed {
      logic        q;
    } smt;
    struct packed {
      logic        q;
    } trie;
  } kraken_padframe_aon_config_reg2hw_pad_gpioa24_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } kraken_padframe_aon_config_reg2hw_pad_gpioa24_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic [1:0]  q;
    } drv;
    struct packed {
      logic        q;
    } pde;
    struct packed {
      logic        q;
    } pue;
    struct packed {
      logic        q;
    } rxe;
    struct packed {
      logic        q;
    } slw;
    struct packed {
      logic        q;
    } smt;
    struct packed {
      logic        q;
    } trie;
  } kraken_padframe_aon_config_reg2hw_pad_gpioa25_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } kraken_padframe_aon_config_reg2hw_pad_gpioa25_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic [1:0]  q;
    } drv;
    struct packed {
      logic        q;
    } pde;
    struct packed {
      logic        q;
    } pue;
    struct packed {
      logic        q;
    } rxe;
    struct packed {
      logic        q;
    } slw;
    struct packed {
      logic        q;
    } smt;
    struct packed {
      logic        q;
    } trie;
  } kraken_padframe_aon_config_reg2hw_pad_gpiob0_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } kraken_padframe_aon_config_reg2hw_pad_gpiob0_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic [1:0]  q;
    } drv;
    struct packed {
      logic        q;
    } pde;
    struct packed {
      logic        q;
    } pue;
    struct packed {
      logic        q;
    } rxe;
    struct packed {
      logic        q;
    } slw;
    struct packed {
      logic        q;
    } smt;
    struct packed {
      logic        q;
    } trie;
  } kraken_padframe_aon_config_reg2hw_pad_gpiob1_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } kraken_padframe_aon_config_reg2hw_pad_gpiob1_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic [1:0]  q;
    } drv;
    struct packed {
      logic        q;
    } pde;
    struct packed {
      logic        q;
    } pue;
    struct packed {
      logic        q;
    } rxe;
    struct packed {
      logic        q;
    } slw;
    struct packed {
      logic        q;
    } smt;
    struct packed {
      logic        q;
    } trie;
  } kraken_padframe_aon_config_reg2hw_pad_gpiob2_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } kraken_padframe_aon_config_reg2hw_pad_gpiob2_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic [1:0]  q;
    } drv;
    struct packed {
      logic        q;
    } pde;
    struct packed {
      logic        q;
    } pue;
    struct packed {
      logic        q;
    } rxe;
    struct packed {
      logic        q;
    } slw;
    struct packed {
      logic        q;
    } smt;
    struct packed {
      logic        q;
    } trie;
  } kraken_padframe_aon_config_reg2hw_pad_gpiob3_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } kraken_padframe_aon_config_reg2hw_pad_gpiob3_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic [1:0]  q;
    } drv;
    struct packed {
      logic        q;
    } pde;
    struct packed {
      logic        q;
    } pue;
    struct packed {
      logic        q;
    } rxe;
    struct packed {
      logic        q;
    } slw;
    struct packed {
      logic        q;
    } smt;
    struct packed {
      logic        q;
    } trie;
  } kraken_padframe_aon_config_reg2hw_pad_gpiob4_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } kraken_padframe_aon_config_reg2hw_pad_gpiob4_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic [1:0]  q;
    } drv;
    struct packed {
      logic        q;
    } pde;
    struct packed {
      logic        q;
    } pue;
    struct packed {
      logic        q;
    } rxe;
    struct packed {
      logic        q;
    } slw;
    struct packed {
      logic        q;
    } smt;
    struct packed {
      logic        q;
    } trie;
  } kraken_padframe_aon_config_reg2hw_pad_gpiob5_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } kraken_padframe_aon_config_reg2hw_pad_gpiob5_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic [1:0]  q;
    } drv;
    struct packed {
      logic        q;
    } pde;
    struct packed {
      logic        q;
    } pue;
    struct packed {
      logic        q;
    } rxe;
    struct packed {
      logic        q;
    } slw;
    struct packed {
      logic        q;
    } smt;
    struct packed {
      logic        q;
    } trie;
  } kraken_padframe_aon_config_reg2hw_pad_gpiob6_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } kraken_padframe_aon_config_reg2hw_pad_gpiob6_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic [1:0]  q;
    } drv;
    struct packed {
      logic        q;
    } pde;
    struct packed {
      logic        q;
    } pue;
    struct packed {
      logic        q;
    } rxe;
    struct packed {
      logic        q;
    } slw;
    struct packed {
      logic        q;
    } smt;
    struct packed {
      logic        q;
    } trie;
  } kraken_padframe_aon_config_reg2hw_pad_gpiob7_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } kraken_padframe_aon_config_reg2hw_pad_gpiob7_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic [1:0]  q;
    } drv;
    struct packed {
      logic        q;
    } pde;
    struct packed {
      logic        q;
    } pue;
    struct packed {
      logic        q;
    } rxe;
    struct packed {
      logic        q;
    } slw;
    struct packed {
      logic        q;
    } smt;
    struct packed {
      logic        q;
    } trie;
  } kraken_padframe_aon_config_reg2hw_pad_gpiob8_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } kraken_padframe_aon_config_reg2hw_pad_gpiob8_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic [1:0]  q;
    } drv;
    struct packed {
      logic        q;
    } pde;
    struct packed {
      logic        q;
    } pue;
    struct packed {
      logic        q;
    } rxe;
    struct packed {
      logic        q;
    } slw;
    struct packed {
      logic        q;
    } smt;
    struct packed {
      logic        q;
    } trie;
  } kraken_padframe_aon_config_reg2hw_pad_gpiob9_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } kraken_padframe_aon_config_reg2hw_pad_gpiob9_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic [1:0]  q;
    } drv;
    struct packed {
      logic        q;
    } pde;
    struct packed {
      logic        q;
    } pue;
    struct packed {
      logic        q;
    } rxe;
    struct packed {
      logic        q;
    } slw;
    struct packed {
      logic        q;
    } smt;
    struct packed {
      logic        q;
    } trie;
  } kraken_padframe_aon_config_reg2hw_pad_gpiob10_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } kraken_padframe_aon_config_reg2hw_pad_gpiob10_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic [1:0]  q;
    } drv;
    struct packed {
      logic        q;
    } pde;
    struct packed {
      logic        q;
    } pue;
    struct packed {
      logic        q;
    } rxe;
    struct packed {
      logic        q;
    } slw;
    struct packed {
      logic        q;
    } smt;
    struct packed {
      logic        q;
    } trie;
  } kraken_padframe_aon_config_reg2hw_pad_gpiob11_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } kraken_padframe_aon_config_reg2hw_pad_gpiob11_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic [1:0]  q;
    } drv;
    struct packed {
      logic        q;
    } pde;
    struct packed {
      logic        q;
    } pue;
    struct packed {
      logic        q;
    } rxe;
    struct packed {
      logic        q;
    } slw;
    struct packed {
      logic        q;
    } smt;
    struct packed {
      logic        q;
    } trie;
  } kraken_padframe_aon_config_reg2hw_pad_gpiob12_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } kraken_padframe_aon_config_reg2hw_pad_gpiob12_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic [1:0]  q;
    } drv;
    struct packed {
      logic        q;
    } pde;
    struct packed {
      logic        q;
    } pue;
    struct packed {
      logic        q;
    } rxe;
    struct packed {
      logic        q;
    } slw;
    struct packed {
      logic        q;
    } smt;
    struct packed {
      logic        q;
    } trie;
  } kraken_padframe_aon_config_reg2hw_pad_gpiob13_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } kraken_padframe_aon_config_reg2hw_pad_gpiob13_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic [1:0]  q;
    } drv;
    struct packed {
      logic        q;
    } pde;
    struct packed {
      logic        q;
    } pue;
    struct packed {
      logic        q;
    } rxe;
    struct packed {
      logic        q;
    } slw;
    struct packed {
      logic        q;
    } smt;
    struct packed {
      logic        q;
    } trie;
  } kraken_padframe_aon_config_reg2hw_pad_gpiob14_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } kraken_padframe_aon_config_reg2hw_pad_gpiob14_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic [1:0]  q;
    } drv;
    struct packed {
      logic        q;
    } pde;
    struct packed {
      logic        q;
    } pue;
    struct packed {
      logic        q;
    } rxe;
    struct packed {
      logic        q;
    } slw;
    struct packed {
      logic        q;
    } smt;
    struct packed {
      logic        q;
    } trie;
  } kraken_padframe_aon_config_reg2hw_pad_gpiob15_cfg_reg_t;

  typedef struct packed {
    logic [5:0]  q;
  } kraken_padframe_aon_config_reg2hw_pad_gpiob15_mux_sel_reg_t;

  // Register -> HW type
  typedef struct packed {
    kraken_padframe_aon_config_reg2hw_info_reg_t info; // [661:630]
    kraken_padframe_aon_config_reg2hw_pad_gpioa0_cfg_reg_t pad_gpioa0_cfg; // [629:621]
    kraken_padframe_aon_config_reg2hw_pad_gpioa0_mux_sel_reg_t pad_gpioa0_mux_sel; // [620:615]
    kraken_padframe_aon_config_reg2hw_pad_gpioa1_cfg_reg_t pad_gpioa1_cfg; // [614:606]
    kraken_padframe_aon_config_reg2hw_pad_gpioa1_mux_sel_reg_t pad_gpioa1_mux_sel; // [605:600]
    kraken_padframe_aon_config_reg2hw_pad_gpioa2_cfg_reg_t pad_gpioa2_cfg; // [599:591]
    kraken_padframe_aon_config_reg2hw_pad_gpioa2_mux_sel_reg_t pad_gpioa2_mux_sel; // [590:585]
    kraken_padframe_aon_config_reg2hw_pad_gpioa3_cfg_reg_t pad_gpioa3_cfg; // [584:576]
    kraken_padframe_aon_config_reg2hw_pad_gpioa3_mux_sel_reg_t pad_gpioa3_mux_sel; // [575:570]
    kraken_padframe_aon_config_reg2hw_pad_gpioa4_cfg_reg_t pad_gpioa4_cfg; // [569:561]
    kraken_padframe_aon_config_reg2hw_pad_gpioa4_mux_sel_reg_t pad_gpioa4_mux_sel; // [560:555]
    kraken_padframe_aon_config_reg2hw_pad_gpioa5_cfg_reg_t pad_gpioa5_cfg; // [554:546]
    kraken_padframe_aon_config_reg2hw_pad_gpioa5_mux_sel_reg_t pad_gpioa5_mux_sel; // [545:540]
    kraken_padframe_aon_config_reg2hw_pad_gpioa6_cfg_reg_t pad_gpioa6_cfg; // [539:531]
    kraken_padframe_aon_config_reg2hw_pad_gpioa6_mux_sel_reg_t pad_gpioa6_mux_sel; // [530:525]
    kraken_padframe_aon_config_reg2hw_pad_gpioa7_cfg_reg_t pad_gpioa7_cfg; // [524:516]
    kraken_padframe_aon_config_reg2hw_pad_gpioa7_mux_sel_reg_t pad_gpioa7_mux_sel; // [515:510]
    kraken_padframe_aon_config_reg2hw_pad_gpioa8_cfg_reg_t pad_gpioa8_cfg; // [509:501]
    kraken_padframe_aon_config_reg2hw_pad_gpioa8_mux_sel_reg_t pad_gpioa8_mux_sel; // [500:495]
    kraken_padframe_aon_config_reg2hw_pad_gpioa9_cfg_reg_t pad_gpioa9_cfg; // [494:486]
    kraken_padframe_aon_config_reg2hw_pad_gpioa9_mux_sel_reg_t pad_gpioa9_mux_sel; // [485:480]
    kraken_padframe_aon_config_reg2hw_pad_gpioa10_cfg_reg_t pad_gpioa10_cfg; // [479:471]
    kraken_padframe_aon_config_reg2hw_pad_gpioa10_mux_sel_reg_t pad_gpioa10_mux_sel; // [470:465]
    kraken_padframe_aon_config_reg2hw_pad_gpioa11_cfg_reg_t pad_gpioa11_cfg; // [464:456]
    kraken_padframe_aon_config_reg2hw_pad_gpioa11_mux_sel_reg_t pad_gpioa11_mux_sel; // [455:450]
    kraken_padframe_aon_config_reg2hw_pad_gpioa12_cfg_reg_t pad_gpioa12_cfg; // [449:441]
    kraken_padframe_aon_config_reg2hw_pad_gpioa12_mux_sel_reg_t pad_gpioa12_mux_sel; // [440:435]
    kraken_padframe_aon_config_reg2hw_pad_gpioa13_cfg_reg_t pad_gpioa13_cfg; // [434:426]
    kraken_padframe_aon_config_reg2hw_pad_gpioa13_mux_sel_reg_t pad_gpioa13_mux_sel; // [425:420]
    kraken_padframe_aon_config_reg2hw_pad_gpioa14_cfg_reg_t pad_gpioa14_cfg; // [419:411]
    kraken_padframe_aon_config_reg2hw_pad_gpioa14_mux_sel_reg_t pad_gpioa14_mux_sel; // [410:405]
    kraken_padframe_aon_config_reg2hw_pad_gpioa15_cfg_reg_t pad_gpioa15_cfg; // [404:396]
    kraken_padframe_aon_config_reg2hw_pad_gpioa15_mux_sel_reg_t pad_gpioa15_mux_sel; // [395:390]
    kraken_padframe_aon_config_reg2hw_pad_gpioa16_cfg_reg_t pad_gpioa16_cfg; // [389:381]
    kraken_padframe_aon_config_reg2hw_pad_gpioa16_mux_sel_reg_t pad_gpioa16_mux_sel; // [380:375]
    kraken_padframe_aon_config_reg2hw_pad_gpioa17_cfg_reg_t pad_gpioa17_cfg; // [374:366]
    kraken_padframe_aon_config_reg2hw_pad_gpioa17_mux_sel_reg_t pad_gpioa17_mux_sel; // [365:360]
    kraken_padframe_aon_config_reg2hw_pad_gpioa18_cfg_reg_t pad_gpioa18_cfg; // [359:351]
    kraken_padframe_aon_config_reg2hw_pad_gpioa18_mux_sel_reg_t pad_gpioa18_mux_sel; // [350:345]
    kraken_padframe_aon_config_reg2hw_pad_gpioa19_cfg_reg_t pad_gpioa19_cfg; // [344:336]
    kraken_padframe_aon_config_reg2hw_pad_gpioa19_mux_sel_reg_t pad_gpioa19_mux_sel; // [335:330]
    kraken_padframe_aon_config_reg2hw_pad_gpioa20_cfg_reg_t pad_gpioa20_cfg; // [329:321]
    kraken_padframe_aon_config_reg2hw_pad_gpioa20_mux_sel_reg_t pad_gpioa20_mux_sel; // [320:315]
    kraken_padframe_aon_config_reg2hw_pad_gpioa21_cfg_reg_t pad_gpioa21_cfg; // [314:306]
    kraken_padframe_aon_config_reg2hw_pad_gpioa21_mux_sel_reg_t pad_gpioa21_mux_sel; // [305:300]
    kraken_padframe_aon_config_reg2hw_pad_gpioa22_cfg_reg_t pad_gpioa22_cfg; // [299:291]
    kraken_padframe_aon_config_reg2hw_pad_gpioa22_mux_sel_reg_t pad_gpioa22_mux_sel; // [290:285]
    kraken_padframe_aon_config_reg2hw_pad_gpioa23_cfg_reg_t pad_gpioa23_cfg; // [284:276]
    kraken_padframe_aon_config_reg2hw_pad_gpioa23_mux_sel_reg_t pad_gpioa23_mux_sel; // [275:270]
    kraken_padframe_aon_config_reg2hw_pad_gpioa24_cfg_reg_t pad_gpioa24_cfg; // [269:261]
    kraken_padframe_aon_config_reg2hw_pad_gpioa24_mux_sel_reg_t pad_gpioa24_mux_sel; // [260:255]
    kraken_padframe_aon_config_reg2hw_pad_gpioa25_cfg_reg_t pad_gpioa25_cfg; // [254:246]
    kraken_padframe_aon_config_reg2hw_pad_gpioa25_mux_sel_reg_t pad_gpioa25_mux_sel; // [245:240]
    kraken_padframe_aon_config_reg2hw_pad_gpiob0_cfg_reg_t pad_gpiob0_cfg; // [239:231]
    kraken_padframe_aon_config_reg2hw_pad_gpiob0_mux_sel_reg_t pad_gpiob0_mux_sel; // [230:225]
    kraken_padframe_aon_config_reg2hw_pad_gpiob1_cfg_reg_t pad_gpiob1_cfg; // [224:216]
    kraken_padframe_aon_config_reg2hw_pad_gpiob1_mux_sel_reg_t pad_gpiob1_mux_sel; // [215:210]
    kraken_padframe_aon_config_reg2hw_pad_gpiob2_cfg_reg_t pad_gpiob2_cfg; // [209:201]
    kraken_padframe_aon_config_reg2hw_pad_gpiob2_mux_sel_reg_t pad_gpiob2_mux_sel; // [200:195]
    kraken_padframe_aon_config_reg2hw_pad_gpiob3_cfg_reg_t pad_gpiob3_cfg; // [194:186]
    kraken_padframe_aon_config_reg2hw_pad_gpiob3_mux_sel_reg_t pad_gpiob3_mux_sel; // [185:180]
    kraken_padframe_aon_config_reg2hw_pad_gpiob4_cfg_reg_t pad_gpiob4_cfg; // [179:171]
    kraken_padframe_aon_config_reg2hw_pad_gpiob4_mux_sel_reg_t pad_gpiob4_mux_sel; // [170:165]
    kraken_padframe_aon_config_reg2hw_pad_gpiob5_cfg_reg_t pad_gpiob5_cfg; // [164:156]
    kraken_padframe_aon_config_reg2hw_pad_gpiob5_mux_sel_reg_t pad_gpiob5_mux_sel; // [155:150]
    kraken_padframe_aon_config_reg2hw_pad_gpiob6_cfg_reg_t pad_gpiob6_cfg; // [149:141]
    kraken_padframe_aon_config_reg2hw_pad_gpiob6_mux_sel_reg_t pad_gpiob6_mux_sel; // [140:135]
    kraken_padframe_aon_config_reg2hw_pad_gpiob7_cfg_reg_t pad_gpiob7_cfg; // [134:126]
    kraken_padframe_aon_config_reg2hw_pad_gpiob7_mux_sel_reg_t pad_gpiob7_mux_sel; // [125:120]
    kraken_padframe_aon_config_reg2hw_pad_gpiob8_cfg_reg_t pad_gpiob8_cfg; // [119:111]
    kraken_padframe_aon_config_reg2hw_pad_gpiob8_mux_sel_reg_t pad_gpiob8_mux_sel; // [110:105]
    kraken_padframe_aon_config_reg2hw_pad_gpiob9_cfg_reg_t pad_gpiob9_cfg; // [104:96]
    kraken_padframe_aon_config_reg2hw_pad_gpiob9_mux_sel_reg_t pad_gpiob9_mux_sel; // [95:90]
    kraken_padframe_aon_config_reg2hw_pad_gpiob10_cfg_reg_t pad_gpiob10_cfg; // [89:81]
    kraken_padframe_aon_config_reg2hw_pad_gpiob10_mux_sel_reg_t pad_gpiob10_mux_sel; // [80:75]
    kraken_padframe_aon_config_reg2hw_pad_gpiob11_cfg_reg_t pad_gpiob11_cfg; // [74:66]
    kraken_padframe_aon_config_reg2hw_pad_gpiob11_mux_sel_reg_t pad_gpiob11_mux_sel; // [65:60]
    kraken_padframe_aon_config_reg2hw_pad_gpiob12_cfg_reg_t pad_gpiob12_cfg; // [59:51]
    kraken_padframe_aon_config_reg2hw_pad_gpiob12_mux_sel_reg_t pad_gpiob12_mux_sel; // [50:45]
    kraken_padframe_aon_config_reg2hw_pad_gpiob13_cfg_reg_t pad_gpiob13_cfg; // [44:36]
    kraken_padframe_aon_config_reg2hw_pad_gpiob13_mux_sel_reg_t pad_gpiob13_mux_sel; // [35:30]
    kraken_padframe_aon_config_reg2hw_pad_gpiob14_cfg_reg_t pad_gpiob14_cfg; // [29:21]
    kraken_padframe_aon_config_reg2hw_pad_gpiob14_mux_sel_reg_t pad_gpiob14_mux_sel; // [20:15]
    kraken_padframe_aon_config_reg2hw_pad_gpiob15_cfg_reg_t pad_gpiob15_cfg; // [14:6]
    kraken_padframe_aon_config_reg2hw_pad_gpiob15_mux_sel_reg_t pad_gpiob15_mux_sel; // [5:0]
  } kraken_padframe_aon_config_reg2hw_t;

  // Register offsets
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_INFO_OFFSET = 9'h 0;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA0_CFG_OFFSET = 9'h 4;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA0_MUX_SEL_OFFSET = 9'h 8;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA1_CFG_OFFSET = 9'h c;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA1_MUX_SEL_OFFSET = 9'h 10;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA2_CFG_OFFSET = 9'h 14;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA2_MUX_SEL_OFFSET = 9'h 18;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA3_CFG_OFFSET = 9'h 1c;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA3_MUX_SEL_OFFSET = 9'h 20;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA4_CFG_OFFSET = 9'h 24;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA4_MUX_SEL_OFFSET = 9'h 28;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA5_CFG_OFFSET = 9'h 2c;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA5_MUX_SEL_OFFSET = 9'h 30;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA6_CFG_OFFSET = 9'h 34;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA6_MUX_SEL_OFFSET = 9'h 38;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA7_CFG_OFFSET = 9'h 3c;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA7_MUX_SEL_OFFSET = 9'h 40;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA8_CFG_OFFSET = 9'h 44;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA8_MUX_SEL_OFFSET = 9'h 48;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA9_CFG_OFFSET = 9'h 4c;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA9_MUX_SEL_OFFSET = 9'h 50;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA10_CFG_OFFSET = 9'h 54;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA10_MUX_SEL_OFFSET = 9'h 58;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA11_CFG_OFFSET = 9'h 5c;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA11_MUX_SEL_OFFSET = 9'h 60;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA12_CFG_OFFSET = 9'h 64;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA12_MUX_SEL_OFFSET = 9'h 68;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA13_CFG_OFFSET = 9'h 6c;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA13_MUX_SEL_OFFSET = 9'h 70;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA14_CFG_OFFSET = 9'h 74;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA14_MUX_SEL_OFFSET = 9'h 78;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA15_CFG_OFFSET = 9'h 7c;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA15_MUX_SEL_OFFSET = 9'h 80;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA16_CFG_OFFSET = 9'h 84;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA16_MUX_SEL_OFFSET = 9'h 88;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA17_CFG_OFFSET = 9'h 8c;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA17_MUX_SEL_OFFSET = 9'h 90;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA18_CFG_OFFSET = 9'h 94;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA18_MUX_SEL_OFFSET = 9'h 98;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA19_CFG_OFFSET = 9'h 9c;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA19_MUX_SEL_OFFSET = 9'h a0;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA20_CFG_OFFSET = 9'h a4;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA20_MUX_SEL_OFFSET = 9'h a8;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA21_CFG_OFFSET = 9'h ac;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA21_MUX_SEL_OFFSET = 9'h b0;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA22_CFG_OFFSET = 9'h b4;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA22_MUX_SEL_OFFSET = 9'h b8;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA23_CFG_OFFSET = 9'h bc;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA23_MUX_SEL_OFFSET = 9'h c0;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA24_CFG_OFFSET = 9'h c4;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA24_MUX_SEL_OFFSET = 9'h c8;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA25_CFG_OFFSET = 9'h cc;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA25_MUX_SEL_OFFSET = 9'h d0;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB0_CFG_OFFSET = 9'h d4;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB0_MUX_SEL_OFFSET = 9'h d8;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB1_CFG_OFFSET = 9'h dc;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB1_MUX_SEL_OFFSET = 9'h e0;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB2_CFG_OFFSET = 9'h e4;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB2_MUX_SEL_OFFSET = 9'h e8;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB3_CFG_OFFSET = 9'h ec;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB3_MUX_SEL_OFFSET = 9'h f0;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB4_CFG_OFFSET = 9'h f4;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB4_MUX_SEL_OFFSET = 9'h f8;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB5_CFG_OFFSET = 9'h fc;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB5_MUX_SEL_OFFSET = 9'h 100;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB6_CFG_OFFSET = 9'h 104;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB6_MUX_SEL_OFFSET = 9'h 108;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB7_CFG_OFFSET = 9'h 10c;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB7_MUX_SEL_OFFSET = 9'h 110;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB8_CFG_OFFSET = 9'h 114;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB8_MUX_SEL_OFFSET = 9'h 118;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB9_CFG_OFFSET = 9'h 11c;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB9_MUX_SEL_OFFSET = 9'h 120;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB10_CFG_OFFSET = 9'h 124;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB10_MUX_SEL_OFFSET = 9'h 128;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB11_CFG_OFFSET = 9'h 12c;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB11_MUX_SEL_OFFSET = 9'h 130;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB12_CFG_OFFSET = 9'h 134;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB12_MUX_SEL_OFFSET = 9'h 138;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB13_CFG_OFFSET = 9'h 13c;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB13_MUX_SEL_OFFSET = 9'h 140;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB14_CFG_OFFSET = 9'h 144;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB14_MUX_SEL_OFFSET = 9'h 148;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB15_CFG_OFFSET = 9'h 14c;
  parameter logic [BlockAw-1:0] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB15_MUX_SEL_OFFSET = 9'h 150;

  // Register index
  typedef enum int {
    KRAKEN_PADFRAME_AON_CONFIG_INFO,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA0_CFG,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA0_MUX_SEL,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA1_CFG,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA1_MUX_SEL,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA2_CFG,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA2_MUX_SEL,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA3_CFG,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA3_MUX_SEL,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA4_CFG,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA4_MUX_SEL,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA5_CFG,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA5_MUX_SEL,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA6_CFG,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA6_MUX_SEL,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA7_CFG,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA7_MUX_SEL,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA8_CFG,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA8_MUX_SEL,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA9_CFG,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA9_MUX_SEL,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA10_CFG,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA10_MUX_SEL,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA11_CFG,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA11_MUX_SEL,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA12_CFG,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA12_MUX_SEL,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA13_CFG,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA13_MUX_SEL,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA14_CFG,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA14_MUX_SEL,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA15_CFG,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA15_MUX_SEL,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA16_CFG,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA16_MUX_SEL,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA17_CFG,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA17_MUX_SEL,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA18_CFG,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA18_MUX_SEL,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA19_CFG,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA19_MUX_SEL,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA20_CFG,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA20_MUX_SEL,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA21_CFG,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA21_MUX_SEL,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA22_CFG,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA22_MUX_SEL,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA23_CFG,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA23_MUX_SEL,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA24_CFG,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA24_MUX_SEL,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA25_CFG,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA25_MUX_SEL,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB0_CFG,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB0_MUX_SEL,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB1_CFG,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB1_MUX_SEL,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB2_CFG,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB2_MUX_SEL,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB3_CFG,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB3_MUX_SEL,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB4_CFG,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB4_MUX_SEL,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB5_CFG,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB5_MUX_SEL,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB6_CFG,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB6_MUX_SEL,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB7_CFG,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB7_MUX_SEL,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB8_CFG,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB8_MUX_SEL,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB9_CFG,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB9_MUX_SEL,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB10_CFG,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB10_MUX_SEL,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB11_CFG,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB11_MUX_SEL,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB12_CFG,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB12_MUX_SEL,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB13_CFG,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB13_MUX_SEL,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB14_CFG,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB14_MUX_SEL,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB15_CFG,
    KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB15_MUX_SEL
  } kraken_padframe_aon_config_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] KRAKEN_PADFRAME_AON_CONFIG_PERMIT [85] = '{
    4'b 1111, // index[ 0] KRAKEN_PADFRAME_AON_CONFIG_INFO
    4'b 0011, // index[ 1] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA0_CFG
    4'b 0001, // index[ 2] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA0_MUX_SEL
    4'b 0011, // index[ 3] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA1_CFG
    4'b 0001, // index[ 4] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA1_MUX_SEL
    4'b 0011, // index[ 5] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA2_CFG
    4'b 0001, // index[ 6] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA2_MUX_SEL
    4'b 0011, // index[ 7] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA3_CFG
    4'b 0001, // index[ 8] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA3_MUX_SEL
    4'b 0011, // index[ 9] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA4_CFG
    4'b 0001, // index[10] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA4_MUX_SEL
    4'b 0011, // index[11] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA5_CFG
    4'b 0001, // index[12] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA5_MUX_SEL
    4'b 0011, // index[13] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA6_CFG
    4'b 0001, // index[14] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA6_MUX_SEL
    4'b 0011, // index[15] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA7_CFG
    4'b 0001, // index[16] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA7_MUX_SEL
    4'b 0011, // index[17] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA8_CFG
    4'b 0001, // index[18] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA8_MUX_SEL
    4'b 0011, // index[19] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA9_CFG
    4'b 0001, // index[20] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA9_MUX_SEL
    4'b 0011, // index[21] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA10_CFG
    4'b 0001, // index[22] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA10_MUX_SEL
    4'b 0011, // index[23] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA11_CFG
    4'b 0001, // index[24] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA11_MUX_SEL
    4'b 0011, // index[25] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA12_CFG
    4'b 0001, // index[26] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA12_MUX_SEL
    4'b 0011, // index[27] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA13_CFG
    4'b 0001, // index[28] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA13_MUX_SEL
    4'b 0011, // index[29] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA14_CFG
    4'b 0001, // index[30] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA14_MUX_SEL
    4'b 0011, // index[31] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA15_CFG
    4'b 0001, // index[32] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA15_MUX_SEL
    4'b 0011, // index[33] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA16_CFG
    4'b 0001, // index[34] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA16_MUX_SEL
    4'b 0011, // index[35] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA17_CFG
    4'b 0001, // index[36] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA17_MUX_SEL
    4'b 0011, // index[37] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA18_CFG
    4'b 0001, // index[38] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA18_MUX_SEL
    4'b 0011, // index[39] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA19_CFG
    4'b 0001, // index[40] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA19_MUX_SEL
    4'b 0011, // index[41] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA20_CFG
    4'b 0001, // index[42] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA20_MUX_SEL
    4'b 0011, // index[43] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA21_CFG
    4'b 0001, // index[44] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA21_MUX_SEL
    4'b 0011, // index[45] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA22_CFG
    4'b 0001, // index[46] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA22_MUX_SEL
    4'b 0011, // index[47] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA23_CFG
    4'b 0001, // index[48] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA23_MUX_SEL
    4'b 0011, // index[49] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA24_CFG
    4'b 0001, // index[50] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA24_MUX_SEL
    4'b 0011, // index[51] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA25_CFG
    4'b 0001, // index[52] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOA25_MUX_SEL
    4'b 0011, // index[53] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB0_CFG
    4'b 0001, // index[54] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB0_MUX_SEL
    4'b 0011, // index[55] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB1_CFG
    4'b 0001, // index[56] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB1_MUX_SEL
    4'b 0011, // index[57] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB2_CFG
    4'b 0001, // index[58] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB2_MUX_SEL
    4'b 0011, // index[59] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB3_CFG
    4'b 0001, // index[60] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB3_MUX_SEL
    4'b 0011, // index[61] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB4_CFG
    4'b 0001, // index[62] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB4_MUX_SEL
    4'b 0011, // index[63] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB5_CFG
    4'b 0001, // index[64] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB5_MUX_SEL
    4'b 0011, // index[65] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB6_CFG
    4'b 0001, // index[66] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB6_MUX_SEL
    4'b 0011, // index[67] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB7_CFG
    4'b 0001, // index[68] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB7_MUX_SEL
    4'b 0011, // index[69] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB8_CFG
    4'b 0001, // index[70] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB8_MUX_SEL
    4'b 0011, // index[71] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB9_CFG
    4'b 0001, // index[72] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB9_MUX_SEL
    4'b 0011, // index[73] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB10_CFG
    4'b 0001, // index[74] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB10_MUX_SEL
    4'b 0011, // index[75] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB11_CFG
    4'b 0001, // index[76] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB11_MUX_SEL
    4'b 0011, // index[77] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB12_CFG
    4'b 0001, // index[78] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB12_MUX_SEL
    4'b 0011, // index[79] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB13_CFG
    4'b 0001, // index[80] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB13_MUX_SEL
    4'b 0011, // index[81] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB14_CFG
    4'b 0001, // index[82] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB14_MUX_SEL
    4'b 0011, // index[83] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB15_CFG
    4'b 0001  // index[84] KRAKEN_PADFRAME_AON_CONFIG_PAD_GPIOB15_MUX_SEL
  };

endpackage

