
module kraken_padframe_aon_pads
  import pkg_kraken_padframe::*;
  import pkg_internal_kraken_padframe_aon::*;
(
  output pad_domain_aon_static_connection_signals_pad2soc_t static_connection_signals_pad2soc,
  input  pad_domain_aon_static_connection_signals_soc2pad_t static_connection_signals_soc2pad,
 // Dynamic Pad control signals, these signals are controlled by the multiplexer in the correpsongin pad_controller module
  input mux_to_pads_t mux_to_pads_i,
  output pads_to_mux_t pads_to_mux_o,
  // Landing Pads
  inout wire logic pad_pad_bypass_fll_pad,
  inout wire logic pad_pad_ext_clk_pad,
  inout wire logic pad_pad_ref_clk_pad,
  inout wire logic pad_pad_bootsel0_pad,
  inout wire logic pad_pad_bootsel1_pad,
  inout wire logic pad_pad_bypass_pad,
  inout wire logic pad_pad_reset_pad,
  inout wire logic pad_pad_jtag_tck_pad,
  inout wire logic pad_pad_jtag_tms_pad,
  inout wire logic pad_pad_jtag_tdi_pad,
  inout wire logic pad_pad_jtag_trstn_pad,
  inout wire logic pad_pad_jtag_tdo_pad,
  inout wire logic pad_pad_hyp_cs0_pad,
  inout wire logic pad_pad_hyp_cs1_pad,
  inout wire logic pad_pad_hyp_ck_pad,
  inout wire logic pad_pad_hyp_ckn_pad,
  inout wire logic pad_pad_hyp_rwds_pad,
  inout wire logic pad_pad_hyp_reset_pad,
  inout wire logic pad_pad_hyp_dq0_pad,
  inout wire logic pad_pad_hyp_dq1_pad,
  inout wire logic pad_pad_hyp_dq2_pad,
  inout wire logic pad_pad_hyp_dq3_pad,
  inout wire logic pad_pad_hyp_dq4_pad,
  inout wire logic pad_pad_hyp_dq5_pad,
  inout wire logic pad_pad_hyp_dq6_pad,
  inout wire logic pad_pad_hyp_dq7_pad,
  inout wire logic pad_pad_gpioa0_pad,
  inout wire logic pad_pad_gpioa1_pad,
  inout wire logic pad_pad_gpioa2_pad,
  inout wire logic pad_pad_gpioa3_pad,
  inout wire logic pad_pad_gpioa4_pad,
  inout wire logic pad_pad_gpioa5_pad,
  inout wire logic pad_pad_gpioa6_pad,
  inout wire logic pad_pad_gpioa7_pad,
  inout wire logic pad_pad_gpioa8_pad,
  inout wire logic pad_pad_gpioa9_pad,
  inout wire logic pad_pad_gpioa10_pad,
  inout wire logic pad_pad_gpioa11_pad,
  inout wire logic pad_pad_gpioa12_pad,
  inout wire logic pad_pad_gpioa13_pad,
  inout wire logic pad_pad_gpioa14_pad,
  inout wire logic pad_pad_gpioa15_pad,
  inout wire logic pad_pad_gpioa16_pad,
  inout wire logic pad_pad_gpioa17_pad,
  inout wire logic pad_pad_gpioa18_pad,
  inout wire logic pad_pad_gpioa19_pad,
  inout wire logic pad_pad_gpioa20_pad,
  inout wire logic pad_pad_gpioa21_pad,
  inout wire logic pad_pad_gpioa22_pad,
  inout wire logic pad_pad_gpioa23_pad,
  inout wire logic pad_pad_gpioa24_pad,
  inout wire logic pad_pad_gpioa25_pad,
  inout wire logic pad_pad_gpiob0_pad,
  inout wire logic pad_pad_gpiob1_pad,
  inout wire logic pad_pad_gpiob2_pad,
  inout wire logic pad_pad_gpiob3_pad,
  inout wire logic pad_pad_gpiob4_pad,
  inout wire logic pad_pad_gpiob5_pad,
  inout wire logic pad_pad_gpiob6_pad,
  inout wire logic pad_pad_gpiob7_pad,
  inout wire logic pad_pad_gpiob8_pad,
  inout wire logic pad_pad_gpiob9_pad,
  inout wire logic pad_pad_gpiob10_pad,
  inout wire logic pad_pad_gpiob11_pad,
  inout wire logic pad_pad_gpiob12_pad,
  inout wire logic pad_pad_gpiob13_pad,
  inout wire logic pad_pad_gpiob14_pad,
  inout wire logic pad_pad_gpiob15_pad
  );

   // Pad instantiations
   wire PWROK_S, IOPWROK_S, BIAS_S, RETC_S;
  
  IN22FDX_GPIO18_10M3S40PI_PWRDET_TIE_V i_pwrdet (
    .RETCOUT (RETC_S),
    .PWROKOUT (PWROK_S),
    .IOPWROKOUT (IOPWROK_S),
    .RETCIN(1'b0),
    .BIAS(BIAS_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_V i_pad_bypass_fll (
    .PAD(pad_pad_bypass_fll_pad),
    .DATA(1'b0),
    .Y(static_connection_signals_pad2soc.st_bypass_fll),
    .TRIEN(1'b1),
    .RXEN(1'b1),
    .PUEN(1'b0),
    .PDEN(1'b0),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(2'b11),
    .SLW(1'b0),
    .SMT(1'b0),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_V i_pad_ext_clk (
    .PAD(pad_pad_ext_clk_pad),
    .DATA(1'b0),
    .Y(static_connection_signals_pad2soc.st_ext_clk),
    .TRIEN(1'b1),
    .RXEN(1'b1),
    .PUEN(1'b0),
    .PDEN(1'b0),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(2'b11),
    .SLW(1'b0),
    .SMT(1'b0),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_V i_pad_ref_clk (
    .PAD(pad_pad_ref_clk_pad),
    .DATA(1'b0),
    .Y(static_connection_signals_pad2soc.st_ref_clk),
    .TRIEN(1'b1),
    .RXEN(1'b1),
    .PUEN(1'b0),
    .PDEN(1'b0),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(2'b11),
    .SLW(1'b0),
    .SMT(1'b0),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_V i_pad_bootsel0 (
    .PAD(pad_pad_bootsel0_pad),
    .DATA(1'b0),
    .Y(static_connection_signals_pad2soc.st_boot_sel0),
    .TRIEN(1'b1),
    .RXEN(1'b1),
    .PUEN(1'b0),
    .PDEN(1'b0),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(2'b11),
    .SLW(1'b0),
    .SMT(1'b0),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_V i_pad_bootsel1 (
    .PAD(pad_pad_bootsel1_pad),
    .DATA(1'b0),
    .Y(static_connection_signals_pad2soc.st_boot_sel1),
    .TRIEN(1'b1),
    .RXEN(1'b1),
    .PUEN(1'b0),
    .PDEN(1'b0),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(2'b11),
    .SLW(1'b0),
    .SMT(1'b0),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_H i_pad_bypass (
    .PAD(pad_pad_bypass_pad),
    .DATA(1'b0),
    .Y(static_connection_signals_pad2soc.st_bypass),
    .TRIEN(1'b1),
    .RXEN(1'b1),
    .PUEN(1'b0),
    .PDEN(1'b0),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(2'b11),
    .SLW(1'b0),
    .SMT(1'b0),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_V i_pad_reset (
    .PAD(pad_pad_reset_pad),
    .DATA(1'b0),
    .Y(static_connection_signals_pad2soc.st_rst_n),
    .TRIEN(1'b1),
    .RXEN(1'b1),
    .PUEN(1'b0),
    .PDEN(1'b0),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(2'b11),
    .SLW(1'b0),
    .SMT(1'b0),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_V i_pad_jtag_tck (
    .PAD(pad_pad_jtag_tck_pad),
    .DATA(1'b0),
    .Y(static_connection_signals_pad2soc.st_jtag_tck),
    .TRIEN(1'b1),
    .RXEN(1'b1),
    .PUEN(1'b0),
    .PDEN(1'b0),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(2'b11),
    .SLW(1'b0),
    .SMT(1'b0),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_V i_pad_jtag_tms (
    .PAD(pad_pad_jtag_tms_pad),
    .DATA(1'b0),
    .Y(static_connection_signals_pad2soc.st_jtag_tms),
    .TRIEN(1'b1),
    .RXEN(1'b1),
    .PUEN(1'b0),
    .PDEN(1'b0),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(2'b11),
    .SLW(1'b0),
    .SMT(1'b0),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_V i_pad_jtag_tdi (
    .PAD(pad_pad_jtag_tdi_pad),
    .DATA(1'b0),
    .Y(static_connection_signals_pad2soc.st_jtag_tdi),
    .TRIEN(1'b1),
    .RXEN(1'b1),
    .PUEN(1'b0),
    .PDEN(1'b0),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(2'b11),
    .SLW(1'b0),
    .SMT(1'b0),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_H i_pad_jtag_trstn (
    .PAD(pad_pad_jtag_trstn_pad),
    .DATA(1'b0),
    .Y(static_connection_signals_pad2soc.st_jtag_trstn),
    .TRIEN(1'b1),
    .RXEN(1'b1),
    .PUEN(1'b0),
    .PDEN(1'b0),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(2'b11),
    .SLW(1'b0),
    .SMT(1'b0),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_V i_pad_jtag_tdo (
    .PAD(pad_pad_jtag_tdo_pad),
    .DATA(static_connection_signals_soc2pad.st_jtag_tdo),
    .Y(),
    .TRIEN(1'b0),
    .RXEN(1'b0),
    .PUEN(1'b0),
    .PDEN(1'b0),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(2'b11),
    .SLW(1'b0),
    .SMT(1'b0),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_V i_pad_hyp_cs0 (
    .PAD(pad_pad_hyp_cs0_pad),
    .DATA(static_connection_signals_soc2pad.st_hyper_cs0_no),
    .Y(),
    .TRIEN(1'b0),
    .RXEN(1'b0),
    .PUEN(1'b0),
    .PDEN(1'b0),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(2'b11),
    .SLW(1'b0),
    .SMT(1'b0),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_V i_pad_hyp_cs1 (
    .PAD(pad_pad_hyp_cs1_pad),
    .DATA(static_connection_signals_soc2pad.st_hyper_cs1_no),
    .Y(),
    .TRIEN(1'b0),
    .RXEN(1'b0),
    .PUEN(1'b0),
    .PDEN(1'b0),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(2'b11),
    .SLW(1'b0),
    .SMT(1'b0),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_V i_pad_hyp_ck (
    .PAD(pad_pad_hyp_ck_pad),
    .DATA(static_connection_signals_soc2pad.st_hyper_ck_o),
    .Y(),
    .TRIEN(1'b0),
    .RXEN(1'b0),
    .PUEN(1'b0),
    .PDEN(1'b0),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(2'b11),
    .SLW(1'b0),
    .SMT(1'b0),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_V i_pad_hyp_ckn (
    .PAD(pad_pad_hyp_ckn_pad),
    .DATA(static_connection_signals_soc2pad.st_hyper_ck_no),
    .Y(),
    .TRIEN(1'b0),
    .RXEN(1'b0),
    .PUEN(1'b0),
    .PDEN(1'b0),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(2'b11),
    .SLW(1'b0),
    .SMT(1'b0),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_V i_pad_hyp_rwds (
    .PAD(pad_pad_hyp_rwds_pad),
    .DATA(static_connection_signals_soc2pad.st_hyper_rwds_o),
    .Y(static_connection_signals_pad2soc.st_hyper_rwds_i),
    .TRIEN(~static_connection_signals_soc2pad.st_hyper_rwds_oe),
    .RXEN(~static_connection_signals_soc2pad.st_hyper_rwds_oe),
    .PUEN(1'b0),
    .PDEN(1'b0),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(2'b11),
    .SLW(1'b0),
    .SMT(1'b0),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_V i_pad_hyp_reset (
    .PAD(pad_pad_hyp_reset_pad),
    .DATA(static_connection_signals_soc2pad.st_hyper_reset_no),
    .Y(),
    .TRIEN(1'b0),
    .RXEN(1'b0),
    .PUEN(1'b0),
    .PDEN(1'b0),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(2'b11),
    .SLW(1'b0),
    .SMT(1'b0),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_V i_pad_hyp_dq0 (
    .PAD(pad_pad_hyp_dq0_pad),
    .DATA(static_connection_signals_soc2pad.st_hyper_dq0_o),
    .Y(static_connection_signals_pad2soc.st_hyper_dq0_i),
    .TRIEN(~static_connection_signals_soc2pad.st_hyper_dq_oe),
    .RXEN(~static_connection_signals_soc2pad.st_hyper_dq_oe),
    .PUEN(1'b0),
    .PDEN(1'b0),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(2'b11),
    .SLW(1'b0),
    .SMT(1'b0),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_V i_pad_hyp_dq1 (
    .PAD(pad_pad_hyp_dq1_pad),
    .DATA(static_connection_signals_soc2pad.st_hyper_dq1_o),
    .Y(static_connection_signals_pad2soc.st_hyper_dq1_i),
    .TRIEN(~static_connection_signals_soc2pad.st_hyper_dq_oe),
    .RXEN(~static_connection_signals_soc2pad.st_hyper_dq_oe),
    .PUEN(1'b0),
    .PDEN(1'b0),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(2'b11),
    .SLW(1'b0),
    .SMT(1'b0),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_V i_pad_hyp_dq2 (
    .PAD(pad_pad_hyp_dq2_pad),
    .DATA(static_connection_signals_soc2pad.st_hyper_dq2_o),
    .Y(static_connection_signals_pad2soc.st_hyper_dq2_i),
    .TRIEN(~static_connection_signals_soc2pad.st_hyper_dq_oe),
    .RXEN(~static_connection_signals_soc2pad.st_hyper_dq_oe),
    .PUEN(1'b0),
    .PDEN(1'b0),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(2'b11),
    .SLW(1'b0),
    .SMT(1'b0),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_V i_pad_hyp_dq3 (
    .PAD(pad_pad_hyp_dq3_pad),
    .DATA(static_connection_signals_soc2pad.st_hyper_dq3_o),
    .Y(static_connection_signals_pad2soc.st_hyper_dq3_i),
    .TRIEN(~static_connection_signals_soc2pad.st_hyper_dq_oe),
    .RXEN(~static_connection_signals_soc2pad.st_hyper_dq_oe),
    .PUEN(1'b0),
    .PDEN(1'b0),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(2'b11),
    .SLW(1'b0),
    .SMT(1'b0),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_V i_pad_hyp_dq4 (
    .PAD(pad_pad_hyp_dq4_pad),
    .DATA(static_connection_signals_soc2pad.st_hyper_dq4_o),
    .Y(static_connection_signals_pad2soc.st_hyper_dq4_i),
    .TRIEN(~static_connection_signals_soc2pad.st_hyper_dq_oe),
    .RXEN(~static_connection_signals_soc2pad.st_hyper_dq_oe),
    .PUEN(1'b0),
    .PDEN(1'b0),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(2'b11),
    .SLW(1'b0),
    .SMT(1'b0),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_V i_pad_hyp_dq5 (
    .PAD(pad_pad_hyp_dq5_pad),
    .DATA(static_connection_signals_soc2pad.st_hyper_dq5_o),
    .Y(static_connection_signals_pad2soc.st_hyper_dq5_i),
    .TRIEN(~static_connection_signals_soc2pad.st_hyper_dq_oe),
    .RXEN(~static_connection_signals_soc2pad.st_hyper_dq_oe),
    .PUEN(1'b0),
    .PDEN(1'b0),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(2'b11),
    .SLW(1'b0),
    .SMT(1'b0),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_V i_pad_hyp_dq6 (
    .PAD(pad_pad_hyp_dq6_pad),
    .DATA(static_connection_signals_soc2pad.st_hyper_dq6_o),
    .Y(static_connection_signals_pad2soc.st_hyper_dq6_i),
    .TRIEN(~static_connection_signals_soc2pad.st_hyper_dq_oe),
    .RXEN(~static_connection_signals_soc2pad.st_hyper_dq_oe),
    .PUEN(1'b0),
    .PDEN(1'b0),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(2'b11),
    .SLW(1'b0),
    .SMT(1'b0),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_V i_pad_hyp_dq7 (
    .PAD(pad_pad_hyp_dq7_pad),
    .DATA(static_connection_signals_soc2pad.st_hyper_dq7_o),
    .Y(static_connection_signals_pad2soc.st_hyper_dq7_i),
    .TRIEN(~static_connection_signals_soc2pad.st_hyper_dq_oe),
    .RXEN(~static_connection_signals_soc2pad.st_hyper_dq_oe),
    .PUEN(1'b0),
    .PDEN(1'b0),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(2'b11),
    .SLW(1'b0),
    .SMT(1'b0),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_H i_pad_gpioa0 (
    .PAD(pad_pad_gpioa0_pad),
    .DATA(mux_to_pads_i.pad_gpioa0.chip2pad),
    .Y(pads_to_mux_o.pad_gpioa0.pad2chip),
    .TRIEN(mux_to_pads_i.pad_gpioa0.trie),
    .RXEN(mux_to_pads_i.pad_gpioa0.rxe),
    .PUEN(mux_to_pads_i.pad_gpioa0.pue),
    .PDEN(mux_to_pads_i.pad_gpioa0.pde),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(mux_to_pads_i.pad_gpioa0.drv),
    .SLW(mux_to_pads_i.pad_gpioa0.slw),
    .SMT(mux_to_pads_i.pad_gpioa0.smt),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_H i_pad_gpioa1 (
    .PAD(pad_pad_gpioa1_pad),
    .DATA(mux_to_pads_i.pad_gpioa1.chip2pad),
    .Y(pads_to_mux_o.pad_gpioa1.pad2chip),
    .TRIEN(mux_to_pads_i.pad_gpioa1.trie),
    .RXEN(mux_to_pads_i.pad_gpioa1.rxe),
    .PUEN(mux_to_pads_i.pad_gpioa1.pue),
    .PDEN(mux_to_pads_i.pad_gpioa1.pde),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(mux_to_pads_i.pad_gpioa1.drv),
    .SLW(mux_to_pads_i.pad_gpioa1.slw),
    .SMT(mux_to_pads_i.pad_gpioa1.smt),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_H i_pad_gpioa2 (
    .PAD(pad_pad_gpioa2_pad),
    .DATA(mux_to_pads_i.pad_gpioa2.chip2pad),
    .Y(pads_to_mux_o.pad_gpioa2.pad2chip),
    .TRIEN(mux_to_pads_i.pad_gpioa2.trie),
    .RXEN(mux_to_pads_i.pad_gpioa2.rxe),
    .PUEN(mux_to_pads_i.pad_gpioa2.pue),
    .PDEN(mux_to_pads_i.pad_gpioa2.pde),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(mux_to_pads_i.pad_gpioa2.drv),
    .SLW(mux_to_pads_i.pad_gpioa2.slw),
    .SMT(mux_to_pads_i.pad_gpioa2.smt),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_H i_pad_gpioa3 (
    .PAD(pad_pad_gpioa3_pad),
    .DATA(mux_to_pads_i.pad_gpioa3.chip2pad),
    .Y(pads_to_mux_o.pad_gpioa3.pad2chip),
    .TRIEN(mux_to_pads_i.pad_gpioa3.trie),
    .RXEN(mux_to_pads_i.pad_gpioa3.rxe),
    .PUEN(mux_to_pads_i.pad_gpioa3.pue),
    .PDEN(mux_to_pads_i.pad_gpioa3.pde),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(mux_to_pads_i.pad_gpioa3.drv),
    .SLW(mux_to_pads_i.pad_gpioa3.slw),
    .SMT(mux_to_pads_i.pad_gpioa3.smt),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_H i_pad_gpioa4 (
    .PAD(pad_pad_gpioa4_pad),
    .DATA(mux_to_pads_i.pad_gpioa4.chip2pad),
    .Y(pads_to_mux_o.pad_gpioa4.pad2chip),
    .TRIEN(mux_to_pads_i.pad_gpioa4.trie),
    .RXEN(mux_to_pads_i.pad_gpioa4.rxe),
    .PUEN(mux_to_pads_i.pad_gpioa4.pue),
    .PDEN(mux_to_pads_i.pad_gpioa4.pde),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(mux_to_pads_i.pad_gpioa4.drv),
    .SLW(mux_to_pads_i.pad_gpioa4.slw),
    .SMT(mux_to_pads_i.pad_gpioa4.smt),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_V i_pad_gpioa5 (
    .PAD(pad_pad_gpioa5_pad),
    .DATA(mux_to_pads_i.pad_gpioa5.chip2pad),
    .Y(pads_to_mux_o.pad_gpioa5.pad2chip),
    .TRIEN(mux_to_pads_i.pad_gpioa5.trie),
    .RXEN(mux_to_pads_i.pad_gpioa5.rxe),
    .PUEN(mux_to_pads_i.pad_gpioa5.pue),
    .PDEN(mux_to_pads_i.pad_gpioa5.pde),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(mux_to_pads_i.pad_gpioa5.drv),
    .SLW(mux_to_pads_i.pad_gpioa5.slw),
    .SMT(mux_to_pads_i.pad_gpioa5.smt),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_V i_pad_gpioa6 (
    .PAD(pad_pad_gpioa6_pad),
    .DATA(mux_to_pads_i.pad_gpioa6.chip2pad),
    .Y(pads_to_mux_o.pad_gpioa6.pad2chip),
    .TRIEN(mux_to_pads_i.pad_gpioa6.trie),
    .RXEN(mux_to_pads_i.pad_gpioa6.rxe),
    .PUEN(mux_to_pads_i.pad_gpioa6.pue),
    .PDEN(mux_to_pads_i.pad_gpioa6.pde),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(mux_to_pads_i.pad_gpioa6.drv),
    .SLW(mux_to_pads_i.pad_gpioa6.slw),
    .SMT(mux_to_pads_i.pad_gpioa6.smt),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_V i_pad_gpioa7 (
    .PAD(pad_pad_gpioa7_pad),
    .DATA(mux_to_pads_i.pad_gpioa7.chip2pad),
    .Y(pads_to_mux_o.pad_gpioa7.pad2chip),
    .TRIEN(mux_to_pads_i.pad_gpioa7.trie),
    .RXEN(mux_to_pads_i.pad_gpioa7.rxe),
    .PUEN(mux_to_pads_i.pad_gpioa7.pue),
    .PDEN(mux_to_pads_i.pad_gpioa7.pde),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(mux_to_pads_i.pad_gpioa7.drv),
    .SLW(mux_to_pads_i.pad_gpioa7.slw),
    .SMT(mux_to_pads_i.pad_gpioa7.smt),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_H i_pad_gpioa8 (
    .PAD(pad_pad_gpioa8_pad),
    .DATA(mux_to_pads_i.pad_gpioa8.chip2pad),
    .Y(pads_to_mux_o.pad_gpioa8.pad2chip),
    .TRIEN(mux_to_pads_i.pad_gpioa8.trie),
    .RXEN(mux_to_pads_i.pad_gpioa8.rxe),
    .PUEN(mux_to_pads_i.pad_gpioa8.pue),
    .PDEN(mux_to_pads_i.pad_gpioa8.pde),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(mux_to_pads_i.pad_gpioa8.drv),
    .SLW(mux_to_pads_i.pad_gpioa8.slw),
    .SMT(mux_to_pads_i.pad_gpioa8.smt),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_H i_pad_gpioa9 (
    .PAD(pad_pad_gpioa9_pad),
    .DATA(mux_to_pads_i.pad_gpioa9.chip2pad),
    .Y(pads_to_mux_o.pad_gpioa9.pad2chip),
    .TRIEN(mux_to_pads_i.pad_gpioa9.trie),
    .RXEN(mux_to_pads_i.pad_gpioa9.rxe),
    .PUEN(mux_to_pads_i.pad_gpioa9.pue),
    .PDEN(mux_to_pads_i.pad_gpioa9.pde),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(mux_to_pads_i.pad_gpioa9.drv),
    .SLW(mux_to_pads_i.pad_gpioa9.slw),
    .SMT(mux_to_pads_i.pad_gpioa9.smt),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_H i_pad_gpioa10 (
    .PAD(pad_pad_gpioa10_pad),
    .DATA(mux_to_pads_i.pad_gpioa10.chip2pad),
    .Y(pads_to_mux_o.pad_gpioa10.pad2chip),
    .TRIEN(mux_to_pads_i.pad_gpioa10.trie),
    .RXEN(mux_to_pads_i.pad_gpioa10.rxe),
    .PUEN(mux_to_pads_i.pad_gpioa10.pue),
    .PDEN(mux_to_pads_i.pad_gpioa10.pde),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(mux_to_pads_i.pad_gpioa10.drv),
    .SLW(mux_to_pads_i.pad_gpioa10.slw),
    .SMT(mux_to_pads_i.pad_gpioa10.smt),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_H i_pad_gpioa11 (
    .PAD(pad_pad_gpioa11_pad),
    .DATA(mux_to_pads_i.pad_gpioa11.chip2pad),
    .Y(pads_to_mux_o.pad_gpioa11.pad2chip),
    .TRIEN(mux_to_pads_i.pad_gpioa11.trie),
    .RXEN(mux_to_pads_i.pad_gpioa11.rxe),
    .PUEN(mux_to_pads_i.pad_gpioa11.pue),
    .PDEN(mux_to_pads_i.pad_gpioa11.pde),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(mux_to_pads_i.pad_gpioa11.drv),
    .SLW(mux_to_pads_i.pad_gpioa11.slw),
    .SMT(mux_to_pads_i.pad_gpioa11.smt),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_H i_pad_gpioa12 (
    .PAD(pad_pad_gpioa12_pad),
    .DATA(mux_to_pads_i.pad_gpioa12.chip2pad),
    .Y(pads_to_mux_o.pad_gpioa12.pad2chip),
    .TRIEN(mux_to_pads_i.pad_gpioa12.trie),
    .RXEN(mux_to_pads_i.pad_gpioa12.rxe),
    .PUEN(mux_to_pads_i.pad_gpioa12.pue),
    .PDEN(mux_to_pads_i.pad_gpioa12.pde),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(mux_to_pads_i.pad_gpioa12.drv),
    .SLW(mux_to_pads_i.pad_gpioa12.slw),
    .SMT(mux_to_pads_i.pad_gpioa12.smt),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_H i_pad_gpioa13 (
    .PAD(pad_pad_gpioa13_pad),
    .DATA(mux_to_pads_i.pad_gpioa13.chip2pad),
    .Y(pads_to_mux_o.pad_gpioa13.pad2chip),
    .TRIEN(mux_to_pads_i.pad_gpioa13.trie),
    .RXEN(mux_to_pads_i.pad_gpioa13.rxe),
    .PUEN(mux_to_pads_i.pad_gpioa13.pue),
    .PDEN(mux_to_pads_i.pad_gpioa13.pde),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(mux_to_pads_i.pad_gpioa13.drv),
    .SLW(mux_to_pads_i.pad_gpioa13.slw),
    .SMT(mux_to_pads_i.pad_gpioa13.smt),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_H i_pad_gpioa14 (
    .PAD(pad_pad_gpioa14_pad),
    .DATA(mux_to_pads_i.pad_gpioa14.chip2pad),
    .Y(pads_to_mux_o.pad_gpioa14.pad2chip),
    .TRIEN(mux_to_pads_i.pad_gpioa14.trie),
    .RXEN(mux_to_pads_i.pad_gpioa14.rxe),
    .PUEN(mux_to_pads_i.pad_gpioa14.pue),
    .PDEN(mux_to_pads_i.pad_gpioa14.pde),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(mux_to_pads_i.pad_gpioa14.drv),
    .SLW(mux_to_pads_i.pad_gpioa14.slw),
    .SMT(mux_to_pads_i.pad_gpioa14.smt),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_H i_pad_gpioa15 (
    .PAD(pad_pad_gpioa15_pad),
    .DATA(mux_to_pads_i.pad_gpioa15.chip2pad),
    .Y(pads_to_mux_o.pad_gpioa15.pad2chip),
    .TRIEN(mux_to_pads_i.pad_gpioa15.trie),
    .RXEN(mux_to_pads_i.pad_gpioa15.rxe),
    .PUEN(mux_to_pads_i.pad_gpioa15.pue),
    .PDEN(mux_to_pads_i.pad_gpioa15.pde),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(mux_to_pads_i.pad_gpioa15.drv),
    .SLW(mux_to_pads_i.pad_gpioa15.slw),
    .SMT(mux_to_pads_i.pad_gpioa15.smt),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_H i_pad_gpioa16 (
    .PAD(pad_pad_gpioa16_pad),
    .DATA(mux_to_pads_i.pad_gpioa16.chip2pad),
    .Y(pads_to_mux_o.pad_gpioa16.pad2chip),
    .TRIEN(mux_to_pads_i.pad_gpioa16.trie),
    .RXEN(mux_to_pads_i.pad_gpioa16.rxe),
    .PUEN(mux_to_pads_i.pad_gpioa16.pue),
    .PDEN(mux_to_pads_i.pad_gpioa16.pde),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(mux_to_pads_i.pad_gpioa16.drv),
    .SLW(mux_to_pads_i.pad_gpioa16.slw),
    .SMT(mux_to_pads_i.pad_gpioa16.smt),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_H i_pad_gpioa17 (
    .PAD(pad_pad_gpioa17_pad),
    .DATA(mux_to_pads_i.pad_gpioa17.chip2pad),
    .Y(pads_to_mux_o.pad_gpioa17.pad2chip),
    .TRIEN(mux_to_pads_i.pad_gpioa17.trie),
    .RXEN(mux_to_pads_i.pad_gpioa17.rxe),
    .PUEN(mux_to_pads_i.pad_gpioa17.pue),
    .PDEN(mux_to_pads_i.pad_gpioa17.pde),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(mux_to_pads_i.pad_gpioa17.drv),
    .SLW(mux_to_pads_i.pad_gpioa17.slw),
    .SMT(mux_to_pads_i.pad_gpioa17.smt),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_H i_pad_gpioa18 (
    .PAD(pad_pad_gpioa18_pad),
    .DATA(mux_to_pads_i.pad_gpioa18.chip2pad),
    .Y(pads_to_mux_o.pad_gpioa18.pad2chip),
    .TRIEN(mux_to_pads_i.pad_gpioa18.trie),
    .RXEN(mux_to_pads_i.pad_gpioa18.rxe),
    .PUEN(mux_to_pads_i.pad_gpioa18.pue),
    .PDEN(mux_to_pads_i.pad_gpioa18.pde),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(mux_to_pads_i.pad_gpioa18.drv),
    .SLW(mux_to_pads_i.pad_gpioa18.slw),
    .SMT(mux_to_pads_i.pad_gpioa18.smt),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_H i_pad_gpioa19 (
    .PAD(pad_pad_gpioa19_pad),
    .DATA(mux_to_pads_i.pad_gpioa19.chip2pad),
    .Y(pads_to_mux_o.pad_gpioa19.pad2chip),
    .TRIEN(mux_to_pads_i.pad_gpioa19.trie),
    .RXEN(mux_to_pads_i.pad_gpioa19.rxe),
    .PUEN(mux_to_pads_i.pad_gpioa19.pue),
    .PDEN(mux_to_pads_i.pad_gpioa19.pde),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(mux_to_pads_i.pad_gpioa19.drv),
    .SLW(mux_to_pads_i.pad_gpioa19.slw),
    .SMT(mux_to_pads_i.pad_gpioa19.smt),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_H i_pad_gpioa20 (
    .PAD(pad_pad_gpioa20_pad),
    .DATA(mux_to_pads_i.pad_gpioa20.chip2pad),
    .Y(pads_to_mux_o.pad_gpioa20.pad2chip),
    .TRIEN(mux_to_pads_i.pad_gpioa20.trie),
    .RXEN(mux_to_pads_i.pad_gpioa20.rxe),
    .PUEN(mux_to_pads_i.pad_gpioa20.pue),
    .PDEN(mux_to_pads_i.pad_gpioa20.pde),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(mux_to_pads_i.pad_gpioa20.drv),
    .SLW(mux_to_pads_i.pad_gpioa20.slw),
    .SMT(mux_to_pads_i.pad_gpioa20.smt),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_H i_pad_gpioa21 (
    .PAD(pad_pad_gpioa21_pad),
    .DATA(mux_to_pads_i.pad_gpioa21.chip2pad),
    .Y(pads_to_mux_o.pad_gpioa21.pad2chip),
    .TRIEN(mux_to_pads_i.pad_gpioa21.trie),
    .RXEN(mux_to_pads_i.pad_gpioa21.rxe),
    .PUEN(mux_to_pads_i.pad_gpioa21.pue),
    .PDEN(mux_to_pads_i.pad_gpioa21.pde),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(mux_to_pads_i.pad_gpioa21.drv),
    .SLW(mux_to_pads_i.pad_gpioa21.slw),
    .SMT(mux_to_pads_i.pad_gpioa21.smt),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_H i_pad_gpioa22 (
    .PAD(pad_pad_gpioa22_pad),
    .DATA(mux_to_pads_i.pad_gpioa22.chip2pad),
    .Y(pads_to_mux_o.pad_gpioa22.pad2chip),
    .TRIEN(mux_to_pads_i.pad_gpioa22.trie),
    .RXEN(mux_to_pads_i.pad_gpioa22.rxe),
    .PUEN(mux_to_pads_i.pad_gpioa22.pue),
    .PDEN(mux_to_pads_i.pad_gpioa22.pde),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(mux_to_pads_i.pad_gpioa22.drv),
    .SLW(mux_to_pads_i.pad_gpioa22.slw),
    .SMT(mux_to_pads_i.pad_gpioa22.smt),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_H i_pad_gpioa23 (
    .PAD(pad_pad_gpioa23_pad),
    .DATA(mux_to_pads_i.pad_gpioa23.chip2pad),
    .Y(pads_to_mux_o.pad_gpioa23.pad2chip),
    .TRIEN(mux_to_pads_i.pad_gpioa23.trie),
    .RXEN(mux_to_pads_i.pad_gpioa23.rxe),
    .PUEN(mux_to_pads_i.pad_gpioa23.pue),
    .PDEN(mux_to_pads_i.pad_gpioa23.pde),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(mux_to_pads_i.pad_gpioa23.drv),
    .SLW(mux_to_pads_i.pad_gpioa23.slw),
    .SMT(mux_to_pads_i.pad_gpioa23.smt),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_H i_pad_gpioa24 (
    .PAD(pad_pad_gpioa24_pad),
    .DATA(mux_to_pads_i.pad_gpioa24.chip2pad),
    .Y(pads_to_mux_o.pad_gpioa24.pad2chip),
    .TRIEN(mux_to_pads_i.pad_gpioa24.trie),
    .RXEN(mux_to_pads_i.pad_gpioa24.rxe),
    .PUEN(mux_to_pads_i.pad_gpioa24.pue),
    .PDEN(mux_to_pads_i.pad_gpioa24.pde),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(mux_to_pads_i.pad_gpioa24.drv),
    .SLW(mux_to_pads_i.pad_gpioa24.slw),
    .SMT(mux_to_pads_i.pad_gpioa24.smt),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_V i_pad_gpioa25 (
    .PAD(pad_pad_gpioa25_pad),
    .DATA(mux_to_pads_i.pad_gpioa25.chip2pad),
    .Y(pads_to_mux_o.pad_gpioa25.pad2chip),
    .TRIEN(mux_to_pads_i.pad_gpioa25.trie),
    .RXEN(mux_to_pads_i.pad_gpioa25.rxe),
    .PUEN(mux_to_pads_i.pad_gpioa25.pue),
    .PDEN(mux_to_pads_i.pad_gpioa25.pde),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(mux_to_pads_i.pad_gpioa25.drv),
    .SLW(mux_to_pads_i.pad_gpioa25.slw),
    .SMT(mux_to_pads_i.pad_gpioa25.smt),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_V i_pad_gpiob0 (
    .PAD(pad_pad_gpiob0_pad),
    .DATA(mux_to_pads_i.pad_gpiob0.chip2pad),
    .Y(pads_to_mux_o.pad_gpiob0.pad2chip),
    .TRIEN(mux_to_pads_i.pad_gpiob0.trie),
    .RXEN(mux_to_pads_i.pad_gpiob0.rxe),
    .PUEN(mux_to_pads_i.pad_gpiob0.pue),
    .PDEN(mux_to_pads_i.pad_gpiob0.pde),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(mux_to_pads_i.pad_gpiob0.drv),
    .SLW(mux_to_pads_i.pad_gpiob0.slw),
    .SMT(mux_to_pads_i.pad_gpiob0.smt),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_V i_pad_gpiob1 (
    .PAD(pad_pad_gpiob1_pad),
    .DATA(mux_to_pads_i.pad_gpiob1.chip2pad),
    .Y(pads_to_mux_o.pad_gpiob1.pad2chip),
    .TRIEN(mux_to_pads_i.pad_gpiob1.trie),
    .RXEN(mux_to_pads_i.pad_gpiob1.rxe),
    .PUEN(mux_to_pads_i.pad_gpiob1.pue),
    .PDEN(mux_to_pads_i.pad_gpiob1.pde),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(mux_to_pads_i.pad_gpiob1.drv),
    .SLW(mux_to_pads_i.pad_gpiob1.slw),
    .SMT(mux_to_pads_i.pad_gpiob1.smt),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_V i_pad_gpiob2 (
    .PAD(pad_pad_gpiob2_pad),
    .DATA(mux_to_pads_i.pad_gpiob2.chip2pad),
    .Y(pads_to_mux_o.pad_gpiob2.pad2chip),
    .TRIEN(mux_to_pads_i.pad_gpiob2.trie),
    .RXEN(mux_to_pads_i.pad_gpiob2.rxe),
    .PUEN(mux_to_pads_i.pad_gpiob2.pue),
    .PDEN(mux_to_pads_i.pad_gpiob2.pde),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(mux_to_pads_i.pad_gpiob2.drv),
    .SLW(mux_to_pads_i.pad_gpiob2.slw),
    .SMT(mux_to_pads_i.pad_gpiob2.smt),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_V i_pad_gpiob3 (
    .PAD(pad_pad_gpiob3_pad),
    .DATA(mux_to_pads_i.pad_gpiob3.chip2pad),
    .Y(pads_to_mux_o.pad_gpiob3.pad2chip),
    .TRIEN(mux_to_pads_i.pad_gpiob3.trie),
    .RXEN(mux_to_pads_i.pad_gpiob3.rxe),
    .PUEN(mux_to_pads_i.pad_gpiob3.pue),
    .PDEN(mux_to_pads_i.pad_gpiob3.pde),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(mux_to_pads_i.pad_gpiob3.drv),
    .SLW(mux_to_pads_i.pad_gpiob3.slw),
    .SMT(mux_to_pads_i.pad_gpiob3.smt),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_V i_pad_gpiob4 (
    .PAD(pad_pad_gpiob4_pad),
    .DATA(mux_to_pads_i.pad_gpiob4.chip2pad),
    .Y(pads_to_mux_o.pad_gpiob4.pad2chip),
    .TRIEN(mux_to_pads_i.pad_gpiob4.trie),
    .RXEN(mux_to_pads_i.pad_gpiob4.rxe),
    .PUEN(mux_to_pads_i.pad_gpiob4.pue),
    .PDEN(mux_to_pads_i.pad_gpiob4.pde),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(mux_to_pads_i.pad_gpiob4.drv),
    .SLW(mux_to_pads_i.pad_gpiob4.slw),
    .SMT(mux_to_pads_i.pad_gpiob4.smt),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_V i_pad_gpiob5 (
    .PAD(pad_pad_gpiob5_pad),
    .DATA(mux_to_pads_i.pad_gpiob5.chip2pad),
    .Y(pads_to_mux_o.pad_gpiob5.pad2chip),
    .TRIEN(mux_to_pads_i.pad_gpiob5.trie),
    .RXEN(mux_to_pads_i.pad_gpiob5.rxe),
    .PUEN(mux_to_pads_i.pad_gpiob5.pue),
    .PDEN(mux_to_pads_i.pad_gpiob5.pde),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(mux_to_pads_i.pad_gpiob5.drv),
    .SLW(mux_to_pads_i.pad_gpiob5.slw),
    .SMT(mux_to_pads_i.pad_gpiob5.smt),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_V i_pad_gpiob6 (
    .PAD(pad_pad_gpiob6_pad),
    .DATA(mux_to_pads_i.pad_gpiob6.chip2pad),
    .Y(pads_to_mux_o.pad_gpiob6.pad2chip),
    .TRIEN(mux_to_pads_i.pad_gpiob6.trie),
    .RXEN(mux_to_pads_i.pad_gpiob6.rxe),
    .PUEN(mux_to_pads_i.pad_gpiob6.pue),
    .PDEN(mux_to_pads_i.pad_gpiob6.pde),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(mux_to_pads_i.pad_gpiob6.drv),
    .SLW(mux_to_pads_i.pad_gpiob6.slw),
    .SMT(mux_to_pads_i.pad_gpiob6.smt),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_V i_pad_gpiob7 (
    .PAD(pad_pad_gpiob7_pad),
    .DATA(mux_to_pads_i.pad_gpiob7.chip2pad),
    .Y(pads_to_mux_o.pad_gpiob7.pad2chip),
    .TRIEN(mux_to_pads_i.pad_gpiob7.trie),
    .RXEN(mux_to_pads_i.pad_gpiob7.rxe),
    .PUEN(mux_to_pads_i.pad_gpiob7.pue),
    .PDEN(mux_to_pads_i.pad_gpiob7.pde),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(mux_to_pads_i.pad_gpiob7.drv),
    .SLW(mux_to_pads_i.pad_gpiob7.slw),
    .SMT(mux_to_pads_i.pad_gpiob7.smt),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_V i_pad_gpiob8 (
    .PAD(pad_pad_gpiob8_pad),
    .DATA(mux_to_pads_i.pad_gpiob8.chip2pad),
    .Y(pads_to_mux_o.pad_gpiob8.pad2chip),
    .TRIEN(mux_to_pads_i.pad_gpiob8.trie),
    .RXEN(mux_to_pads_i.pad_gpiob8.rxe),
    .PUEN(mux_to_pads_i.pad_gpiob8.pue),
    .PDEN(mux_to_pads_i.pad_gpiob8.pde),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(mux_to_pads_i.pad_gpiob8.drv),
    .SLW(mux_to_pads_i.pad_gpiob8.slw),
    .SMT(mux_to_pads_i.pad_gpiob8.smt),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_V i_pad_gpiob9 (
    .PAD(pad_pad_gpiob9_pad),
    .DATA(mux_to_pads_i.pad_gpiob9.chip2pad),
    .Y(pads_to_mux_o.pad_gpiob9.pad2chip),
    .TRIEN(mux_to_pads_i.pad_gpiob9.trie),
    .RXEN(mux_to_pads_i.pad_gpiob9.rxe),
    .PUEN(mux_to_pads_i.pad_gpiob9.pue),
    .PDEN(mux_to_pads_i.pad_gpiob9.pde),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(mux_to_pads_i.pad_gpiob9.drv),
    .SLW(mux_to_pads_i.pad_gpiob9.slw),
    .SMT(mux_to_pads_i.pad_gpiob9.smt),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_V i_pad_gpiob10 (
    .PAD(pad_pad_gpiob10_pad),
    .DATA(mux_to_pads_i.pad_gpiob10.chip2pad),
    .Y(pads_to_mux_o.pad_gpiob10.pad2chip),
    .TRIEN(mux_to_pads_i.pad_gpiob10.trie),
    .RXEN(mux_to_pads_i.pad_gpiob10.rxe),
    .PUEN(mux_to_pads_i.pad_gpiob10.pue),
    .PDEN(mux_to_pads_i.pad_gpiob10.pde),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(mux_to_pads_i.pad_gpiob10.drv),
    .SLW(mux_to_pads_i.pad_gpiob10.slw),
    .SMT(mux_to_pads_i.pad_gpiob10.smt),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_V i_pad_gpiob11 (
    .PAD(pad_pad_gpiob11_pad),
    .DATA(mux_to_pads_i.pad_gpiob11.chip2pad),
    .Y(pads_to_mux_o.pad_gpiob11.pad2chip),
    .TRIEN(mux_to_pads_i.pad_gpiob11.trie),
    .RXEN(mux_to_pads_i.pad_gpiob11.rxe),
    .PUEN(mux_to_pads_i.pad_gpiob11.pue),
    .PDEN(mux_to_pads_i.pad_gpiob11.pde),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(mux_to_pads_i.pad_gpiob11.drv),
    .SLW(mux_to_pads_i.pad_gpiob11.slw),
    .SMT(mux_to_pads_i.pad_gpiob11.smt),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_V i_pad_gpiob12 (
    .PAD(pad_pad_gpiob12_pad),
    .DATA(mux_to_pads_i.pad_gpiob12.chip2pad),
    .Y(pads_to_mux_o.pad_gpiob12.pad2chip),
    .TRIEN(mux_to_pads_i.pad_gpiob12.trie),
    .RXEN(mux_to_pads_i.pad_gpiob12.rxe),
    .PUEN(mux_to_pads_i.pad_gpiob12.pue),
    .PDEN(mux_to_pads_i.pad_gpiob12.pde),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(mux_to_pads_i.pad_gpiob12.drv),
    .SLW(mux_to_pads_i.pad_gpiob12.slw),
    .SMT(mux_to_pads_i.pad_gpiob12.smt),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_V i_pad_gpiob13 (
    .PAD(pad_pad_gpiob13_pad),
    .DATA(mux_to_pads_i.pad_gpiob13.chip2pad),
    .Y(pads_to_mux_o.pad_gpiob13.pad2chip),
    .TRIEN(mux_to_pads_i.pad_gpiob13.trie),
    .RXEN(mux_to_pads_i.pad_gpiob13.rxe),
    .PUEN(mux_to_pads_i.pad_gpiob13.pue),
    .PDEN(mux_to_pads_i.pad_gpiob13.pde),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(mux_to_pads_i.pad_gpiob13.drv),
    .SLW(mux_to_pads_i.pad_gpiob13.slw),
    .SMT(mux_to_pads_i.pad_gpiob13.smt),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_V i_pad_gpiob14 (
    .PAD(pad_pad_gpiob14_pad),
    .DATA(mux_to_pads_i.pad_gpiob14.chip2pad),
    .Y(pads_to_mux_o.pad_gpiob14.pad2chip),
    .TRIEN(mux_to_pads_i.pad_gpiob14.trie),
    .RXEN(mux_to_pads_i.pad_gpiob14.rxe),
    .PUEN(mux_to_pads_i.pad_gpiob14.pue),
    .PDEN(mux_to_pads_i.pad_gpiob14.pde),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(mux_to_pads_i.pad_gpiob14.drv),
    .SLW(mux_to_pads_i.pad_gpiob14.slw),
    .SMT(mux_to_pads_i.pad_gpiob14.smt),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );
   IN22FDX_GPIO18_10M3S40PI_IO_V i_pad_gpiob15 (
    .PAD(pad_pad_gpiob15_pad),
    .DATA(mux_to_pads_i.pad_gpiob15.chip2pad),
    .Y(pads_to_mux_o.pad_gpiob15.pad2chip),
    .TRIEN(mux_to_pads_i.pad_gpiob15.trie),
    .RXEN(mux_to_pads_i.pad_gpiob15.rxe),
    .PUEN(mux_to_pads_i.pad_gpiob15.pue),
    .PDEN(mux_to_pads_i.pad_gpiob15.pde),
    .NDIN(1'b0),
    .NDOUT(),
    .DRV(mux_to_pads_i.pad_gpiob15.drv),
    .SLW(mux_to_pads_i.pad_gpiob15.slw),
    .SMT(mux_to_pads_i.pad_gpiob15.smt),
    .PWROK(PWROK_S),
    .IOPWROK(IOPWROK_S),
    .BIAS(BIAS_S),
    .RETC(RETC_S)
  );

endmodule : kraken_padframe_aon_pads
