// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package low_power_padframe_always_on_pads_config_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 10;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    struct packed {
      logic [15:0] q;
    } hw_version;
    struct packed {
      logic [15:0] q;
    } padcount;
  } low_power_padframe_always_on_pads_config_reg2hw_info_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa0_cfg_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa0_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa1_cfg_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa1_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa2_cfg_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa2_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa3_cfg_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa3_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa4_cfg_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa4_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa5_cfg_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa5_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa6_cfg_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa6_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa7_cfg_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa7_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa8_cfg_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa8_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa9_cfg_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa9_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa10_cfg_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa10_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa11_cfg_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa11_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa12_cfg_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa12_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa13_cfg_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa13_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa14_cfg_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa14_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa15_cfg_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa15_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa16_cfg_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa16_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa17_cfg_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa17_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa18_cfg_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa18_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa19_cfg_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa19_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa20_cfg_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa20_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa21_cfg_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa21_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa22_cfg_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa22_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa23_cfg_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa23_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa24_cfg_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa24_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa25_cfg_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa25_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa26_cfg_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa26_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa27_cfg_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa27_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa28_cfg_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa28_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa29_cfg_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa29_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa30_cfg_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa30_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa31_cfg_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa31_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob0_cfg_reg_t;

  typedef struct packed {
    logic [1:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob0_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob1_cfg_reg_t;

  typedef struct packed {
    logic [1:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob1_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob2_cfg_reg_t;

  typedef struct packed {
    logic [1:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob2_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob3_cfg_reg_t;

  typedef struct packed {
    logic [1:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob3_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob4_cfg_reg_t;

  typedef struct packed {
    logic [1:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob4_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob5_cfg_reg_t;

  typedef struct packed {
    logic [1:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob5_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob6_cfg_reg_t;

  typedef struct packed {
    logic [1:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob6_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob7_cfg_reg_t;

  typedef struct packed {
    logic [1:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob7_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob8_cfg_reg_t;

  typedef struct packed {
    logic [1:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob8_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob9_cfg_reg_t;

  typedef struct packed {
    logic [1:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob9_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob10_cfg_reg_t;

  typedef struct packed {
    logic [1:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob10_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob11_cfg_reg_t;

  typedef struct packed {
    logic [1:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob11_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob12_cfg_reg_t;

  typedef struct packed {
    logic [1:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob12_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob13_cfg_reg_t;

  typedef struct packed {
    logic [1:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob13_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob14_cfg_reg_t;

  typedef struct packed {
    logic [1:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob14_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob15_cfg_reg_t;

  typedef struct packed {
    logic [1:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob15_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob16_cfg_reg_t;

  typedef struct packed {
    logic [1:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob16_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob17_cfg_reg_t;

  typedef struct packed {
    logic [1:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob17_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob18_cfg_reg_t;

  typedef struct packed {
    logic [1:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob18_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob19_cfg_reg_t;

  typedef struct packed {
    logic [1:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob19_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob20_cfg_reg_t;

  typedef struct packed {
    logic [1:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob20_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob21_cfg_reg_t;

  typedef struct packed {
    logic [1:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob21_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob22_cfg_reg_t;

  typedef struct packed {
    logic [1:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob22_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob23_cfg_reg_t;

  typedef struct packed {
    logic [1:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob23_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob24_cfg_reg_t;

  typedef struct packed {
    logic [1:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob24_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob25_cfg_reg_t;

  typedef struct packed {
    logic [1:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob25_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob26_cfg_reg_t;

  typedef struct packed {
    logic [1:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob26_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob27_cfg_reg_t;

  typedef struct packed {
    logic [1:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob27_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob28_cfg_reg_t;

  typedef struct packed {
    logic [1:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob28_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob29_cfg_reg_t;

  typedef struct packed {
    logic [1:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob29_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob30_cfg_reg_t;

  typedef struct packed {
    logic [1:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob30_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob31_cfg_reg_t;

  typedef struct packed {
    logic [1:0]  q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob31_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc0_cfg_reg_t;

  typedef struct packed {
    logic        q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc0_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc1_cfg_reg_t;

  typedef struct packed {
    logic        q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc1_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc2_cfg_reg_t;

  typedef struct packed {
    logic        q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc2_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc3_cfg_reg_t;

  typedef struct packed {
    logic        q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc3_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc4_cfg_reg_t;

  typedef struct packed {
    logic        q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc4_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc5_cfg_reg_t;

  typedef struct packed {
    logic        q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc5_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc6_cfg_reg_t;

  typedef struct packed {
    logic        q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc6_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc7_cfg_reg_t;

  typedef struct packed {
    logic        q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc7_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc8_cfg_reg_t;

  typedef struct packed {
    logic        q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc8_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc9_cfg_reg_t;

  typedef struct packed {
    logic        q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc9_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc10_cfg_reg_t;

  typedef struct packed {
    logic        q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc10_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc11_cfg_reg_t;

  typedef struct packed {
    logic        q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc11_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc12_cfg_reg_t;

  typedef struct packed {
    logic        q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc12_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc13_cfg_reg_t;

  typedef struct packed {
    logic        q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc13_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc14_cfg_reg_t;

  typedef struct packed {
    logic        q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc14_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_up_en;
    struct packed {
      logic        q;
    } rx_en;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc15_cfg_reg_t;

  typedef struct packed {
    logic        q;
  } low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc15_mux_sel_reg_t;

  // Register -> HW type
  typedef struct packed {
    low_power_padframe_always_on_pads_config_reg2hw_info_reg_t info; // [527:496]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa0_cfg_reg_t pad_gpioa0_cfg; // [495:492]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa0_mux_sel_reg_t pad_gpioa0_mux_sel; // [491:489]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa1_cfg_reg_t pad_gpioa1_cfg; // [488:485]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa1_mux_sel_reg_t pad_gpioa1_mux_sel; // [484:482]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa2_cfg_reg_t pad_gpioa2_cfg; // [481:478]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa2_mux_sel_reg_t pad_gpioa2_mux_sel; // [477:475]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa3_cfg_reg_t pad_gpioa3_cfg; // [474:471]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa3_mux_sel_reg_t pad_gpioa3_mux_sel; // [470:468]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa4_cfg_reg_t pad_gpioa4_cfg; // [467:464]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa4_mux_sel_reg_t pad_gpioa4_mux_sel; // [463:461]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa5_cfg_reg_t pad_gpioa5_cfg; // [460:457]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa5_mux_sel_reg_t pad_gpioa5_mux_sel; // [456:454]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa6_cfg_reg_t pad_gpioa6_cfg; // [453:450]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa6_mux_sel_reg_t pad_gpioa6_mux_sel; // [449:447]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa7_cfg_reg_t pad_gpioa7_cfg; // [446:443]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa7_mux_sel_reg_t pad_gpioa7_mux_sel; // [442:440]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa8_cfg_reg_t pad_gpioa8_cfg; // [439:436]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa8_mux_sel_reg_t pad_gpioa8_mux_sel; // [435:433]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa9_cfg_reg_t pad_gpioa9_cfg; // [432:429]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa9_mux_sel_reg_t pad_gpioa9_mux_sel; // [428:426]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa10_cfg_reg_t pad_gpioa10_cfg; // [425:422]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa10_mux_sel_reg_t pad_gpioa10_mux_sel; // [421:419]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa11_cfg_reg_t pad_gpioa11_cfg; // [418:415]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa11_mux_sel_reg_t pad_gpioa11_mux_sel; // [414:412]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa12_cfg_reg_t pad_gpioa12_cfg; // [411:408]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa12_mux_sel_reg_t pad_gpioa12_mux_sel; // [407:405]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa13_cfg_reg_t pad_gpioa13_cfg; // [404:401]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa13_mux_sel_reg_t pad_gpioa13_mux_sel; // [400:398]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa14_cfg_reg_t pad_gpioa14_cfg; // [397:394]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa14_mux_sel_reg_t pad_gpioa14_mux_sel; // [393:391]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa15_cfg_reg_t pad_gpioa15_cfg; // [390:387]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa15_mux_sel_reg_t pad_gpioa15_mux_sel; // [386:384]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa16_cfg_reg_t pad_gpioa16_cfg; // [383:380]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa16_mux_sel_reg_t pad_gpioa16_mux_sel; // [379:377]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa17_cfg_reg_t pad_gpioa17_cfg; // [376:373]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa17_mux_sel_reg_t pad_gpioa17_mux_sel; // [372:370]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa18_cfg_reg_t pad_gpioa18_cfg; // [369:366]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa18_mux_sel_reg_t pad_gpioa18_mux_sel; // [365:363]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa19_cfg_reg_t pad_gpioa19_cfg; // [362:359]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa19_mux_sel_reg_t pad_gpioa19_mux_sel; // [358:356]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa20_cfg_reg_t pad_gpioa20_cfg; // [355:352]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa20_mux_sel_reg_t pad_gpioa20_mux_sel; // [351:349]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa21_cfg_reg_t pad_gpioa21_cfg; // [348:345]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa21_mux_sel_reg_t pad_gpioa21_mux_sel; // [344:342]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa22_cfg_reg_t pad_gpioa22_cfg; // [341:338]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa22_mux_sel_reg_t pad_gpioa22_mux_sel; // [337:335]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa23_cfg_reg_t pad_gpioa23_cfg; // [334:331]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa23_mux_sel_reg_t pad_gpioa23_mux_sel; // [330:328]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa24_cfg_reg_t pad_gpioa24_cfg; // [327:324]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa24_mux_sel_reg_t pad_gpioa24_mux_sel; // [323:321]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa25_cfg_reg_t pad_gpioa25_cfg; // [320:317]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa25_mux_sel_reg_t pad_gpioa25_mux_sel; // [316:314]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa26_cfg_reg_t pad_gpioa26_cfg; // [313:310]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa26_mux_sel_reg_t pad_gpioa26_mux_sel; // [309:307]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa27_cfg_reg_t pad_gpioa27_cfg; // [306:303]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa27_mux_sel_reg_t pad_gpioa27_mux_sel; // [302:300]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa28_cfg_reg_t pad_gpioa28_cfg; // [299:296]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa28_mux_sel_reg_t pad_gpioa28_mux_sel; // [295:293]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa29_cfg_reg_t pad_gpioa29_cfg; // [292:289]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa29_mux_sel_reg_t pad_gpioa29_mux_sel; // [288:286]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa30_cfg_reg_t pad_gpioa30_cfg; // [285:282]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa30_mux_sel_reg_t pad_gpioa30_mux_sel; // [281:279]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa31_cfg_reg_t pad_gpioa31_cfg; // [278:275]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioa31_mux_sel_reg_t pad_gpioa31_mux_sel; // [274:272]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob0_cfg_reg_t pad_gpiob0_cfg; // [271:268]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob0_mux_sel_reg_t pad_gpiob0_mux_sel; // [267:266]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob1_cfg_reg_t pad_gpiob1_cfg; // [265:262]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob1_mux_sel_reg_t pad_gpiob1_mux_sel; // [261:260]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob2_cfg_reg_t pad_gpiob2_cfg; // [259:256]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob2_mux_sel_reg_t pad_gpiob2_mux_sel; // [255:254]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob3_cfg_reg_t pad_gpiob3_cfg; // [253:250]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob3_mux_sel_reg_t pad_gpiob3_mux_sel; // [249:248]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob4_cfg_reg_t pad_gpiob4_cfg; // [247:244]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob4_mux_sel_reg_t pad_gpiob4_mux_sel; // [243:242]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob5_cfg_reg_t pad_gpiob5_cfg; // [241:238]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob5_mux_sel_reg_t pad_gpiob5_mux_sel; // [237:236]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob6_cfg_reg_t pad_gpiob6_cfg; // [235:232]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob6_mux_sel_reg_t pad_gpiob6_mux_sel; // [231:230]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob7_cfg_reg_t pad_gpiob7_cfg; // [229:226]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob7_mux_sel_reg_t pad_gpiob7_mux_sel; // [225:224]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob8_cfg_reg_t pad_gpiob8_cfg; // [223:220]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob8_mux_sel_reg_t pad_gpiob8_mux_sel; // [219:218]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob9_cfg_reg_t pad_gpiob9_cfg; // [217:214]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob9_mux_sel_reg_t pad_gpiob9_mux_sel; // [213:212]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob10_cfg_reg_t pad_gpiob10_cfg; // [211:208]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob10_mux_sel_reg_t pad_gpiob10_mux_sel; // [207:206]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob11_cfg_reg_t pad_gpiob11_cfg; // [205:202]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob11_mux_sel_reg_t pad_gpiob11_mux_sel; // [201:200]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob12_cfg_reg_t pad_gpiob12_cfg; // [199:196]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob12_mux_sel_reg_t pad_gpiob12_mux_sel; // [195:194]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob13_cfg_reg_t pad_gpiob13_cfg; // [193:190]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob13_mux_sel_reg_t pad_gpiob13_mux_sel; // [189:188]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob14_cfg_reg_t pad_gpiob14_cfg; // [187:184]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob14_mux_sel_reg_t pad_gpiob14_mux_sel; // [183:182]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob15_cfg_reg_t pad_gpiob15_cfg; // [181:178]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob15_mux_sel_reg_t pad_gpiob15_mux_sel; // [177:176]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob16_cfg_reg_t pad_gpiob16_cfg; // [175:172]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob16_mux_sel_reg_t pad_gpiob16_mux_sel; // [171:170]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob17_cfg_reg_t pad_gpiob17_cfg; // [169:166]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob17_mux_sel_reg_t pad_gpiob17_mux_sel; // [165:164]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob18_cfg_reg_t pad_gpiob18_cfg; // [163:160]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob18_mux_sel_reg_t pad_gpiob18_mux_sel; // [159:158]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob19_cfg_reg_t pad_gpiob19_cfg; // [157:154]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob19_mux_sel_reg_t pad_gpiob19_mux_sel; // [153:152]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob20_cfg_reg_t pad_gpiob20_cfg; // [151:148]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob20_mux_sel_reg_t pad_gpiob20_mux_sel; // [147:146]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob21_cfg_reg_t pad_gpiob21_cfg; // [145:142]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob21_mux_sel_reg_t pad_gpiob21_mux_sel; // [141:140]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob22_cfg_reg_t pad_gpiob22_cfg; // [139:136]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob22_mux_sel_reg_t pad_gpiob22_mux_sel; // [135:134]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob23_cfg_reg_t pad_gpiob23_cfg; // [133:130]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob23_mux_sel_reg_t pad_gpiob23_mux_sel; // [129:128]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob24_cfg_reg_t pad_gpiob24_cfg; // [127:124]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob24_mux_sel_reg_t pad_gpiob24_mux_sel; // [123:122]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob25_cfg_reg_t pad_gpiob25_cfg; // [121:118]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob25_mux_sel_reg_t pad_gpiob25_mux_sel; // [117:116]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob26_cfg_reg_t pad_gpiob26_cfg; // [115:112]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob26_mux_sel_reg_t pad_gpiob26_mux_sel; // [111:110]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob27_cfg_reg_t pad_gpiob27_cfg; // [109:106]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob27_mux_sel_reg_t pad_gpiob27_mux_sel; // [105:104]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob28_cfg_reg_t pad_gpiob28_cfg; // [103:100]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob28_mux_sel_reg_t pad_gpiob28_mux_sel; // [99:98]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob29_cfg_reg_t pad_gpiob29_cfg; // [97:94]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob29_mux_sel_reg_t pad_gpiob29_mux_sel; // [93:92]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob30_cfg_reg_t pad_gpiob30_cfg; // [91:88]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob30_mux_sel_reg_t pad_gpiob30_mux_sel; // [87:86]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob31_cfg_reg_t pad_gpiob31_cfg; // [85:82]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpiob31_mux_sel_reg_t pad_gpiob31_mux_sel; // [81:80]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc0_cfg_reg_t pad_gpioc0_cfg; // [79:76]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc0_mux_sel_reg_t pad_gpioc0_mux_sel; // [75:75]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc1_cfg_reg_t pad_gpioc1_cfg; // [74:71]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc1_mux_sel_reg_t pad_gpioc1_mux_sel; // [70:70]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc2_cfg_reg_t pad_gpioc2_cfg; // [69:66]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc2_mux_sel_reg_t pad_gpioc2_mux_sel; // [65:65]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc3_cfg_reg_t pad_gpioc3_cfg; // [64:61]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc3_mux_sel_reg_t pad_gpioc3_mux_sel; // [60:60]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc4_cfg_reg_t pad_gpioc4_cfg; // [59:56]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc4_mux_sel_reg_t pad_gpioc4_mux_sel; // [55:55]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc5_cfg_reg_t pad_gpioc5_cfg; // [54:51]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc5_mux_sel_reg_t pad_gpioc5_mux_sel; // [50:50]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc6_cfg_reg_t pad_gpioc6_cfg; // [49:46]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc6_mux_sel_reg_t pad_gpioc6_mux_sel; // [45:45]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc7_cfg_reg_t pad_gpioc7_cfg; // [44:41]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc7_mux_sel_reg_t pad_gpioc7_mux_sel; // [40:40]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc8_cfg_reg_t pad_gpioc8_cfg; // [39:36]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc8_mux_sel_reg_t pad_gpioc8_mux_sel; // [35:35]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc9_cfg_reg_t pad_gpioc9_cfg; // [34:31]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc9_mux_sel_reg_t pad_gpioc9_mux_sel; // [30:30]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc10_cfg_reg_t pad_gpioc10_cfg; // [29:26]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc10_mux_sel_reg_t pad_gpioc10_mux_sel; // [25:25]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc11_cfg_reg_t pad_gpioc11_cfg; // [24:21]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc11_mux_sel_reg_t pad_gpioc11_mux_sel; // [20:20]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc12_cfg_reg_t pad_gpioc12_cfg; // [19:16]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc12_mux_sel_reg_t pad_gpioc12_mux_sel; // [15:15]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc13_cfg_reg_t pad_gpioc13_cfg; // [14:11]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc13_mux_sel_reg_t pad_gpioc13_mux_sel; // [10:10]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc14_cfg_reg_t pad_gpioc14_cfg; // [9:6]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc14_mux_sel_reg_t pad_gpioc14_mux_sel; // [5:5]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc15_cfg_reg_t pad_gpioc15_cfg; // [4:1]
    low_power_padframe_always_on_pads_config_reg2hw_pad_gpioc15_mux_sel_reg_t pad_gpioc15_mux_sel; // [0:0]
  } low_power_padframe_always_on_pads_config_reg2hw_t;

  // Register offsets
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_INFO_OFFSET = 10'h 0;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA0_CFG_OFFSET = 10'h 4;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA0_MUX_SEL_OFFSET = 10'h 8;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA1_CFG_OFFSET = 10'h c;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA1_MUX_SEL_OFFSET = 10'h 10;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA2_CFG_OFFSET = 10'h 14;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA2_MUX_SEL_OFFSET = 10'h 18;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA3_CFG_OFFSET = 10'h 1c;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA3_MUX_SEL_OFFSET = 10'h 20;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA4_CFG_OFFSET = 10'h 24;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA4_MUX_SEL_OFFSET = 10'h 28;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA5_CFG_OFFSET = 10'h 2c;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA5_MUX_SEL_OFFSET = 10'h 30;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA6_CFG_OFFSET = 10'h 34;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA6_MUX_SEL_OFFSET = 10'h 38;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA7_CFG_OFFSET = 10'h 3c;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA7_MUX_SEL_OFFSET = 10'h 40;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA8_CFG_OFFSET = 10'h 44;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA8_MUX_SEL_OFFSET = 10'h 48;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA9_CFG_OFFSET = 10'h 4c;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA9_MUX_SEL_OFFSET = 10'h 50;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA10_CFG_OFFSET = 10'h 54;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA10_MUX_SEL_OFFSET = 10'h 58;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA11_CFG_OFFSET = 10'h 5c;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA11_MUX_SEL_OFFSET = 10'h 60;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA12_CFG_OFFSET = 10'h 64;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA12_MUX_SEL_OFFSET = 10'h 68;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA13_CFG_OFFSET = 10'h 6c;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA13_MUX_SEL_OFFSET = 10'h 70;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA14_CFG_OFFSET = 10'h 74;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA14_MUX_SEL_OFFSET = 10'h 78;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA15_CFG_OFFSET = 10'h 7c;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA15_MUX_SEL_OFFSET = 10'h 80;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA16_CFG_OFFSET = 10'h 84;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA16_MUX_SEL_OFFSET = 10'h 88;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA17_CFG_OFFSET = 10'h 8c;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA17_MUX_SEL_OFFSET = 10'h 90;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA18_CFG_OFFSET = 10'h 94;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA18_MUX_SEL_OFFSET = 10'h 98;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA19_CFG_OFFSET = 10'h 9c;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA19_MUX_SEL_OFFSET = 10'h a0;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA20_CFG_OFFSET = 10'h a4;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA20_MUX_SEL_OFFSET = 10'h a8;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA21_CFG_OFFSET = 10'h ac;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA21_MUX_SEL_OFFSET = 10'h b0;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA22_CFG_OFFSET = 10'h b4;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA22_MUX_SEL_OFFSET = 10'h b8;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA23_CFG_OFFSET = 10'h bc;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA23_MUX_SEL_OFFSET = 10'h c0;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA24_CFG_OFFSET = 10'h c4;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA24_MUX_SEL_OFFSET = 10'h c8;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA25_CFG_OFFSET = 10'h cc;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA25_MUX_SEL_OFFSET = 10'h d0;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA26_CFG_OFFSET = 10'h d4;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA26_MUX_SEL_OFFSET = 10'h d8;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA27_CFG_OFFSET = 10'h dc;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA27_MUX_SEL_OFFSET = 10'h e0;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA28_CFG_OFFSET = 10'h e4;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA28_MUX_SEL_OFFSET = 10'h e8;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA29_CFG_OFFSET = 10'h ec;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA29_MUX_SEL_OFFSET = 10'h f0;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA30_CFG_OFFSET = 10'h f4;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA30_MUX_SEL_OFFSET = 10'h f8;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA31_CFG_OFFSET = 10'h fc;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA31_MUX_SEL_OFFSET = 10'h 100;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB0_CFG_OFFSET = 10'h 104;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB0_MUX_SEL_OFFSET = 10'h 108;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB1_CFG_OFFSET = 10'h 10c;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB1_MUX_SEL_OFFSET = 10'h 110;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB2_CFG_OFFSET = 10'h 114;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB2_MUX_SEL_OFFSET = 10'h 118;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB3_CFG_OFFSET = 10'h 11c;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB3_MUX_SEL_OFFSET = 10'h 120;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB4_CFG_OFFSET = 10'h 124;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB4_MUX_SEL_OFFSET = 10'h 128;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB5_CFG_OFFSET = 10'h 12c;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB5_MUX_SEL_OFFSET = 10'h 130;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB6_CFG_OFFSET = 10'h 134;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB6_MUX_SEL_OFFSET = 10'h 138;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB7_CFG_OFFSET = 10'h 13c;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB7_MUX_SEL_OFFSET = 10'h 140;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB8_CFG_OFFSET = 10'h 144;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB8_MUX_SEL_OFFSET = 10'h 148;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB9_CFG_OFFSET = 10'h 14c;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB9_MUX_SEL_OFFSET = 10'h 150;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB10_CFG_OFFSET = 10'h 154;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB10_MUX_SEL_OFFSET = 10'h 158;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB11_CFG_OFFSET = 10'h 15c;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB11_MUX_SEL_OFFSET = 10'h 160;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB12_CFG_OFFSET = 10'h 164;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB12_MUX_SEL_OFFSET = 10'h 168;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB13_CFG_OFFSET = 10'h 16c;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB13_MUX_SEL_OFFSET = 10'h 170;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB14_CFG_OFFSET = 10'h 174;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB14_MUX_SEL_OFFSET = 10'h 178;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB15_CFG_OFFSET = 10'h 17c;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB15_MUX_SEL_OFFSET = 10'h 180;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB16_CFG_OFFSET = 10'h 184;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB16_MUX_SEL_OFFSET = 10'h 188;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB17_CFG_OFFSET = 10'h 18c;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB17_MUX_SEL_OFFSET = 10'h 190;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB18_CFG_OFFSET = 10'h 194;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB18_MUX_SEL_OFFSET = 10'h 198;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB19_CFG_OFFSET = 10'h 19c;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB19_MUX_SEL_OFFSET = 10'h 1a0;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB20_CFG_OFFSET = 10'h 1a4;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB20_MUX_SEL_OFFSET = 10'h 1a8;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB21_CFG_OFFSET = 10'h 1ac;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB21_MUX_SEL_OFFSET = 10'h 1b0;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB22_CFG_OFFSET = 10'h 1b4;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB22_MUX_SEL_OFFSET = 10'h 1b8;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB23_CFG_OFFSET = 10'h 1bc;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB23_MUX_SEL_OFFSET = 10'h 1c0;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB24_CFG_OFFSET = 10'h 1c4;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB24_MUX_SEL_OFFSET = 10'h 1c8;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB25_CFG_OFFSET = 10'h 1cc;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB25_MUX_SEL_OFFSET = 10'h 1d0;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB26_CFG_OFFSET = 10'h 1d4;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB26_MUX_SEL_OFFSET = 10'h 1d8;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB27_CFG_OFFSET = 10'h 1dc;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB27_MUX_SEL_OFFSET = 10'h 1e0;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB28_CFG_OFFSET = 10'h 1e4;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB28_MUX_SEL_OFFSET = 10'h 1e8;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB29_CFG_OFFSET = 10'h 1ec;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB29_MUX_SEL_OFFSET = 10'h 1f0;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB30_CFG_OFFSET = 10'h 1f4;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB30_MUX_SEL_OFFSET = 10'h 1f8;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB31_CFG_OFFSET = 10'h 1fc;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB31_MUX_SEL_OFFSET = 10'h 200;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC0_CFG_OFFSET = 10'h 204;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC0_MUX_SEL_OFFSET = 10'h 208;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC1_CFG_OFFSET = 10'h 20c;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC1_MUX_SEL_OFFSET = 10'h 210;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC2_CFG_OFFSET = 10'h 214;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC2_MUX_SEL_OFFSET = 10'h 218;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC3_CFG_OFFSET = 10'h 21c;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC3_MUX_SEL_OFFSET = 10'h 220;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC4_CFG_OFFSET = 10'h 224;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC4_MUX_SEL_OFFSET = 10'h 228;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC5_CFG_OFFSET = 10'h 22c;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC5_MUX_SEL_OFFSET = 10'h 230;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC6_CFG_OFFSET = 10'h 234;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC6_MUX_SEL_OFFSET = 10'h 238;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC7_CFG_OFFSET = 10'h 23c;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC7_MUX_SEL_OFFSET = 10'h 240;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC8_CFG_OFFSET = 10'h 244;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC8_MUX_SEL_OFFSET = 10'h 248;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC9_CFG_OFFSET = 10'h 24c;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC9_MUX_SEL_OFFSET = 10'h 250;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC10_CFG_OFFSET = 10'h 254;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC10_MUX_SEL_OFFSET = 10'h 258;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC11_CFG_OFFSET = 10'h 25c;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC11_MUX_SEL_OFFSET = 10'h 260;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC12_CFG_OFFSET = 10'h 264;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC12_MUX_SEL_OFFSET = 10'h 268;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC13_CFG_OFFSET = 10'h 26c;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC13_MUX_SEL_OFFSET = 10'h 270;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC14_CFG_OFFSET = 10'h 274;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC14_MUX_SEL_OFFSET = 10'h 278;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC15_CFG_OFFSET = 10'h 27c;
  parameter logic [BlockAw-1:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC15_MUX_SEL_OFFSET = 10'h 280;

  // Register index
  typedef enum int {
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_INFO,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA0_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA0_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA1_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA1_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA2_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA2_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA3_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA3_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA4_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA4_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA5_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA5_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA6_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA6_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA7_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA7_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA8_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA8_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA9_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA9_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA10_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA10_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA11_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA11_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA12_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA12_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA13_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA13_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA14_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA14_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA15_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA15_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA16_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA16_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA17_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA17_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA18_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA18_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA19_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA19_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA20_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA20_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA21_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA21_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA22_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA22_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA23_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA23_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA24_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA24_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA25_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA25_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA26_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA26_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA27_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA27_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA28_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA28_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA29_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA29_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA30_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA30_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA31_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA31_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB0_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB0_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB1_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB1_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB2_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB2_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB3_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB3_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB4_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB4_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB5_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB5_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB6_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB6_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB7_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB7_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB8_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB8_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB9_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB9_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB10_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB10_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB11_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB11_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB12_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB12_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB13_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB13_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB14_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB14_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB15_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB15_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB16_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB16_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB17_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB17_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB18_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB18_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB19_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB19_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB20_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB20_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB21_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB21_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB22_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB22_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB23_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB23_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB24_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB24_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB25_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB25_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB26_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB26_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB27_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB27_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB28_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB28_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB29_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB29_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB30_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB30_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB31_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB31_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC0_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC0_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC1_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC1_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC2_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC2_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC3_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC3_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC4_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC4_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC5_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC5_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC6_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC6_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC7_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC7_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC8_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC8_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC9_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC9_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC10_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC10_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC11_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC11_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC12_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC12_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC13_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC13_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC14_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC14_MUX_SEL,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC15_CFG,
    LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC15_MUX_SEL
  } low_power_padframe_always_on_pads_config_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PERMIT [161] = '{
    4'b 1111, // index[  0] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_INFO
    4'b 0001, // index[  1] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA0_CFG
    4'b 0001, // index[  2] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA0_MUX_SEL
    4'b 0001, // index[  3] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA1_CFG
    4'b 0001, // index[  4] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA1_MUX_SEL
    4'b 0001, // index[  5] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA2_CFG
    4'b 0001, // index[  6] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA2_MUX_SEL
    4'b 0001, // index[  7] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA3_CFG
    4'b 0001, // index[  8] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA3_MUX_SEL
    4'b 0001, // index[  9] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA4_CFG
    4'b 0001, // index[ 10] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA4_MUX_SEL
    4'b 0001, // index[ 11] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA5_CFG
    4'b 0001, // index[ 12] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA5_MUX_SEL
    4'b 0001, // index[ 13] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA6_CFG
    4'b 0001, // index[ 14] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA6_MUX_SEL
    4'b 0001, // index[ 15] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA7_CFG
    4'b 0001, // index[ 16] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA7_MUX_SEL
    4'b 0001, // index[ 17] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA8_CFG
    4'b 0001, // index[ 18] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA8_MUX_SEL
    4'b 0001, // index[ 19] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA9_CFG
    4'b 0001, // index[ 20] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA9_MUX_SEL
    4'b 0001, // index[ 21] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA10_CFG
    4'b 0001, // index[ 22] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA10_MUX_SEL
    4'b 0001, // index[ 23] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA11_CFG
    4'b 0001, // index[ 24] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA11_MUX_SEL
    4'b 0001, // index[ 25] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA12_CFG
    4'b 0001, // index[ 26] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA12_MUX_SEL
    4'b 0001, // index[ 27] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA13_CFG
    4'b 0001, // index[ 28] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA13_MUX_SEL
    4'b 0001, // index[ 29] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA14_CFG
    4'b 0001, // index[ 30] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA14_MUX_SEL
    4'b 0001, // index[ 31] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA15_CFG
    4'b 0001, // index[ 32] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA15_MUX_SEL
    4'b 0001, // index[ 33] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA16_CFG
    4'b 0001, // index[ 34] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA16_MUX_SEL
    4'b 0001, // index[ 35] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA17_CFG
    4'b 0001, // index[ 36] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA17_MUX_SEL
    4'b 0001, // index[ 37] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA18_CFG
    4'b 0001, // index[ 38] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA18_MUX_SEL
    4'b 0001, // index[ 39] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA19_CFG
    4'b 0001, // index[ 40] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA19_MUX_SEL
    4'b 0001, // index[ 41] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA20_CFG
    4'b 0001, // index[ 42] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA20_MUX_SEL
    4'b 0001, // index[ 43] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA21_CFG
    4'b 0001, // index[ 44] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA21_MUX_SEL
    4'b 0001, // index[ 45] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA22_CFG
    4'b 0001, // index[ 46] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA22_MUX_SEL
    4'b 0001, // index[ 47] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA23_CFG
    4'b 0001, // index[ 48] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA23_MUX_SEL
    4'b 0001, // index[ 49] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA24_CFG
    4'b 0001, // index[ 50] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA24_MUX_SEL
    4'b 0001, // index[ 51] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA25_CFG
    4'b 0001, // index[ 52] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA25_MUX_SEL
    4'b 0001, // index[ 53] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA26_CFG
    4'b 0001, // index[ 54] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA26_MUX_SEL
    4'b 0001, // index[ 55] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA27_CFG
    4'b 0001, // index[ 56] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA27_MUX_SEL
    4'b 0001, // index[ 57] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA28_CFG
    4'b 0001, // index[ 58] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA28_MUX_SEL
    4'b 0001, // index[ 59] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA29_CFG
    4'b 0001, // index[ 60] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA29_MUX_SEL
    4'b 0001, // index[ 61] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA30_CFG
    4'b 0001, // index[ 62] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA30_MUX_SEL
    4'b 0001, // index[ 63] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA31_CFG
    4'b 0001, // index[ 64] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOA31_MUX_SEL
    4'b 0001, // index[ 65] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB0_CFG
    4'b 0001, // index[ 66] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB0_MUX_SEL
    4'b 0001, // index[ 67] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB1_CFG
    4'b 0001, // index[ 68] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB1_MUX_SEL
    4'b 0001, // index[ 69] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB2_CFG
    4'b 0001, // index[ 70] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB2_MUX_SEL
    4'b 0001, // index[ 71] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB3_CFG
    4'b 0001, // index[ 72] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB3_MUX_SEL
    4'b 0001, // index[ 73] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB4_CFG
    4'b 0001, // index[ 74] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB4_MUX_SEL
    4'b 0001, // index[ 75] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB5_CFG
    4'b 0001, // index[ 76] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB5_MUX_SEL
    4'b 0001, // index[ 77] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB6_CFG
    4'b 0001, // index[ 78] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB6_MUX_SEL
    4'b 0001, // index[ 79] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB7_CFG
    4'b 0001, // index[ 80] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB7_MUX_SEL
    4'b 0001, // index[ 81] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB8_CFG
    4'b 0001, // index[ 82] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB8_MUX_SEL
    4'b 0001, // index[ 83] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB9_CFG
    4'b 0001, // index[ 84] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB9_MUX_SEL
    4'b 0001, // index[ 85] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB10_CFG
    4'b 0001, // index[ 86] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB10_MUX_SEL
    4'b 0001, // index[ 87] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB11_CFG
    4'b 0001, // index[ 88] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB11_MUX_SEL
    4'b 0001, // index[ 89] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB12_CFG
    4'b 0001, // index[ 90] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB12_MUX_SEL
    4'b 0001, // index[ 91] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB13_CFG
    4'b 0001, // index[ 92] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB13_MUX_SEL
    4'b 0001, // index[ 93] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB14_CFG
    4'b 0001, // index[ 94] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB14_MUX_SEL
    4'b 0001, // index[ 95] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB15_CFG
    4'b 0001, // index[ 96] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB15_MUX_SEL
    4'b 0001, // index[ 97] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB16_CFG
    4'b 0001, // index[ 98] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB16_MUX_SEL
    4'b 0001, // index[ 99] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB17_CFG
    4'b 0001, // index[100] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB17_MUX_SEL
    4'b 0001, // index[101] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB18_CFG
    4'b 0001, // index[102] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB18_MUX_SEL
    4'b 0001, // index[103] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB19_CFG
    4'b 0001, // index[104] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB19_MUX_SEL
    4'b 0001, // index[105] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB20_CFG
    4'b 0001, // index[106] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB20_MUX_SEL
    4'b 0001, // index[107] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB21_CFG
    4'b 0001, // index[108] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB21_MUX_SEL
    4'b 0001, // index[109] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB22_CFG
    4'b 0001, // index[110] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB22_MUX_SEL
    4'b 0001, // index[111] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB23_CFG
    4'b 0001, // index[112] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB23_MUX_SEL
    4'b 0001, // index[113] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB24_CFG
    4'b 0001, // index[114] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB24_MUX_SEL
    4'b 0001, // index[115] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB25_CFG
    4'b 0001, // index[116] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB25_MUX_SEL
    4'b 0001, // index[117] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB26_CFG
    4'b 0001, // index[118] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB26_MUX_SEL
    4'b 0001, // index[119] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB27_CFG
    4'b 0001, // index[120] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB27_MUX_SEL
    4'b 0001, // index[121] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB28_CFG
    4'b 0001, // index[122] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB28_MUX_SEL
    4'b 0001, // index[123] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB29_CFG
    4'b 0001, // index[124] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB29_MUX_SEL
    4'b 0001, // index[125] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB30_CFG
    4'b 0001, // index[126] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB30_MUX_SEL
    4'b 0001, // index[127] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB31_CFG
    4'b 0001, // index[128] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOB31_MUX_SEL
    4'b 0001, // index[129] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC0_CFG
    4'b 0001, // index[130] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC0_MUX_SEL
    4'b 0001, // index[131] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC1_CFG
    4'b 0001, // index[132] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC1_MUX_SEL
    4'b 0001, // index[133] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC2_CFG
    4'b 0001, // index[134] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC2_MUX_SEL
    4'b 0001, // index[135] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC3_CFG
    4'b 0001, // index[136] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC3_MUX_SEL
    4'b 0001, // index[137] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC4_CFG
    4'b 0001, // index[138] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC4_MUX_SEL
    4'b 0001, // index[139] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC5_CFG
    4'b 0001, // index[140] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC5_MUX_SEL
    4'b 0001, // index[141] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC6_CFG
    4'b 0001, // index[142] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC6_MUX_SEL
    4'b 0001, // index[143] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC7_CFG
    4'b 0001, // index[144] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC7_MUX_SEL
    4'b 0001, // index[145] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC8_CFG
    4'b 0001, // index[146] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC8_MUX_SEL
    4'b 0001, // index[147] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC9_CFG
    4'b 0001, // index[148] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC9_MUX_SEL
    4'b 0001, // index[149] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC10_CFG
    4'b 0001, // index[150] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC10_MUX_SEL
    4'b 0001, // index[151] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC11_CFG
    4'b 0001, // index[152] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC11_MUX_SEL
    4'b 0001, // index[153] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC12_CFG
    4'b 0001, // index[154] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC12_MUX_SEL
    4'b 0001, // index[155] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC13_CFG
    4'b 0001, // index[156] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC13_MUX_SEL
    4'b 0001, // index[157] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC14_CFG
    4'b 0001, // index[158] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC14_MUX_SEL
    4'b 0001, // index[159] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC15_CFG
    4'b 0001  // index[160] LOW_POWER_PADFRAME_ALWAYS_ON_PADS_CONFIG_PAD_GPIOC15_MUX_SEL
  };

endpackage

