
module low_power_padframe_always_on_pads
  import pkg_low_power_padframe::*;
  import pkg_internal_low_power_padframe_always_on_pads::*;
#(
  parameter type              req_t  = logic, // reg_interface request type
  parameter type             resp_t  = logic // reg_interface response type
) (
  input logic clk_i,
  input logic rst_ni,
  input pad_domain_always_on_pads_override_signals_t override_signals_i,
  output pad_domain_always_on_pads_static_connection_signals_pad2soc_t static_connection_signals_pad2soc,
  output pad_domain_always_on_pads_ports_pad2soc_t port_signals_pad2soc_o,
  input pad_domain_always_on_pads_ports_soc2pad_t port_signals_soc2pad_i,
  inout wire logic pad_pad_ref_clk_pad,
  inout wire logic pad_pad_gpioa0_pad,
  inout wire logic pad_pad_gpioa1_pad,
  inout wire logic pad_pad_gpioa2_pad,
  inout wire logic pad_pad_gpioa3_pad,
  inout wire logic pad_pad_gpioa4_pad,
  inout wire logic pad_pad_gpioa5_pad,
  inout wire logic pad_pad_gpioa6_pad,
  inout wire logic pad_pad_gpioa7_pad,
  inout wire logic pad_pad_gpioa8_pad,
  inout wire logic pad_pad_gpioa9_pad,
  inout wire logic pad_pad_gpioa10_pad,
  inout wire logic pad_pad_gpioa11_pad,
  inout wire logic pad_pad_gpioa12_pad,
  inout wire logic pad_pad_gpioa13_pad,
  inout wire logic pad_pad_gpioa14_pad,
  inout wire logic pad_pad_gpioa15_pad,
  inout wire logic pad_pad_gpioa16_pad,
  inout wire logic pad_pad_gpioa17_pad,
  inout wire logic pad_pad_gpioa18_pad,
  inout wire logic pad_pad_gpioa19_pad,
  inout wire logic pad_pad_gpioa20_pad,
  inout wire logic pad_pad_gpioa21_pad,
  inout wire logic pad_pad_gpioa22_pad,
  inout wire logic pad_pad_gpioa23_pad,
  inout wire logic pad_pad_gpioa24_pad,
  inout wire logic pad_pad_gpioa25_pad,
  inout wire logic pad_pad_gpioa26_pad,
  inout wire logic pad_pad_gpioa27_pad,
  inout wire logic pad_pad_gpioa28_pad,
  inout wire logic pad_pad_gpioa29_pad,
  inout wire logic pad_pad_gpioa30_pad,
  inout wire logic pad_pad_gpioa31_pad,
  inout wire logic pad_pad_gpiob0_pad,
  inout wire logic pad_pad_gpiob1_pad,
  inout wire logic pad_pad_gpiob2_pad,
  inout wire logic pad_pad_gpiob3_pad,
  inout wire logic pad_pad_gpiob4_pad,
  inout wire logic pad_pad_gpiob5_pad,
  inout wire logic pad_pad_gpiob6_pad,
  inout wire logic pad_pad_gpiob7_pad,
  inout wire logic pad_pad_gpiob8_pad,
  inout wire logic pad_pad_gpiob9_pad,
  inout wire logic pad_pad_gpiob10_pad,
  inout wire logic pad_pad_gpiob11_pad,
  inout wire logic pad_pad_gpiob12_pad,
  inout wire logic pad_pad_gpiob13_pad,
  inout wire logic pad_pad_gpiob14_pad,
  inout wire logic pad_pad_gpiob15_pad,
  inout wire logic pad_pad_gpiob16_pad,
  inout wire logic pad_pad_gpiob17_pad,
  inout wire logic pad_pad_gpiob18_pad,
  inout wire logic pad_pad_gpiob19_pad,
  inout wire logic pad_pad_gpiob20_pad,
  inout wire logic pad_pad_gpiob21_pad,
  inout wire logic pad_pad_gpiob22_pad,
  inout wire logic pad_pad_gpiob23_pad,
  inout wire logic pad_pad_gpiob24_pad,
  inout wire logic pad_pad_gpiob25_pad,
  inout wire logic pad_pad_gpiob26_pad,
  inout wire logic pad_pad_gpiob27_pad,
  inout wire logic pad_pad_gpiob28_pad,
  inout wire logic pad_pad_gpiob29_pad,
  inout wire logic pad_pad_gpiob30_pad,
  inout wire logic pad_pad_gpiob31_pad,
  inout wire logic pad_pad_gpioc0_pad,
  inout wire logic pad_pad_gpioc1_pad,
  inout wire logic pad_pad_gpioc2_pad,
  inout wire logic pad_pad_gpioc3_pad,
  inout wire logic pad_pad_gpioc4_pad,
  inout wire logic pad_pad_gpioc5_pad,
  inout wire logic pad_pad_gpioc6_pad,
  inout wire logic pad_pad_gpioc7_pad,
  inout wire logic pad_pad_gpioc8_pad,
  inout wire logic pad_pad_gpioc9_pad,
  inout wire logic pad_pad_gpioc10_pad,
  inout wire logic pad_pad_gpioc11_pad,
  inout wire logic pad_pad_gpioc12_pad,
  inout wire logic pad_pad_gpioc13_pad,
  inout wire logic pad_pad_gpioc14_pad,
  inout wire logic pad_pad_gpioc15_pad,
  input req_t config_req_i,
  output resp_t config_rsp_o
);

   mux_to_pads_t s_mux_to_pads;
   pads_to_mux_t s_pads_to_mux;

   low_power_padframe_always_on_pads_pads i_always_on_pads_pads (
     .override_signals_i,
     .static_connection_signals_pad2soc,
     .mux_to_pads_i(s_mux_to_pads),
     .pads_to_mux_o(s_pads_to_mux),
     .pad_pad_ref_clk_pad,
     .pad_pad_gpioa0_pad,
     .pad_pad_gpioa1_pad,
     .pad_pad_gpioa2_pad,
     .pad_pad_gpioa3_pad,
     .pad_pad_gpioa4_pad,
     .pad_pad_gpioa5_pad,
     .pad_pad_gpioa6_pad,
     .pad_pad_gpioa7_pad,
     .pad_pad_gpioa8_pad,
     .pad_pad_gpioa9_pad,
     .pad_pad_gpioa10_pad,
     .pad_pad_gpioa11_pad,
     .pad_pad_gpioa12_pad,
     .pad_pad_gpioa13_pad,
     .pad_pad_gpioa14_pad,
     .pad_pad_gpioa15_pad,
     .pad_pad_gpioa16_pad,
     .pad_pad_gpioa17_pad,
     .pad_pad_gpioa18_pad,
     .pad_pad_gpioa19_pad,
     .pad_pad_gpioa20_pad,
     .pad_pad_gpioa21_pad,
     .pad_pad_gpioa22_pad,
     .pad_pad_gpioa23_pad,
     .pad_pad_gpioa24_pad,
     .pad_pad_gpioa25_pad,
     .pad_pad_gpioa26_pad,
     .pad_pad_gpioa27_pad,
     .pad_pad_gpioa28_pad,
     .pad_pad_gpioa29_pad,
     .pad_pad_gpioa30_pad,
     .pad_pad_gpioa31_pad,
     .pad_pad_gpiob0_pad,
     .pad_pad_gpiob1_pad,
     .pad_pad_gpiob2_pad,
     .pad_pad_gpiob3_pad,
     .pad_pad_gpiob4_pad,
     .pad_pad_gpiob5_pad,
     .pad_pad_gpiob6_pad,
     .pad_pad_gpiob7_pad,
     .pad_pad_gpiob8_pad,
     .pad_pad_gpiob9_pad,
     .pad_pad_gpiob10_pad,
     .pad_pad_gpiob11_pad,
     .pad_pad_gpiob12_pad,
     .pad_pad_gpiob13_pad,
     .pad_pad_gpiob14_pad,
     .pad_pad_gpiob15_pad,
     .pad_pad_gpiob16_pad,
     .pad_pad_gpiob17_pad,
     .pad_pad_gpiob18_pad,
     .pad_pad_gpiob19_pad,
     .pad_pad_gpiob20_pad,
     .pad_pad_gpiob21_pad,
     .pad_pad_gpiob22_pad,
     .pad_pad_gpiob23_pad,
     .pad_pad_gpiob24_pad,
     .pad_pad_gpiob25_pad,
     .pad_pad_gpiob26_pad,
     .pad_pad_gpiob27_pad,
     .pad_pad_gpiob28_pad,
     .pad_pad_gpiob29_pad,
     .pad_pad_gpiob30_pad,
     .pad_pad_gpiob31_pad,
     .pad_pad_gpioc0_pad,
     .pad_pad_gpioc1_pad,
     .pad_pad_gpioc2_pad,
     .pad_pad_gpioc3_pad,
     .pad_pad_gpioc4_pad,
     .pad_pad_gpioc5_pad,
     .pad_pad_gpioc6_pad,
     .pad_pad_gpioc7_pad,
     .pad_pad_gpioc8_pad,
     .pad_pad_gpioc9_pad,
     .pad_pad_gpioc10_pad,
     .pad_pad_gpioc11_pad,
     .pad_pad_gpioc12_pad,
     .pad_pad_gpioc13_pad,
     .pad_pad_gpioc14_pad,
     .pad_pad_gpioc15_pad

  );

   low_power_padframe_always_on_pads_muxer #(
     .req_t(req_t),
     .resp_t(resp_t)
   )i_always_on_pads_muxer (
     .clk_i,
     .rst_ni,
     .port_signals_soc2pad_i,
     .port_signals_pad2soc_o,
     .mux_to_pads_o(s_mux_to_pads),
     .pads_to_mux_i(s_pads_to_mux),
     // Configuration interface using register_interface protocol
     .config_req_i,
     .config_rsp_o
   );

endmodule : low_power_padframe_always_on_pads
